'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

export default function BoundaryConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [scopeName, setScopeName] = useState('my-org');
  const [projectName, setProjectName] = useState('my-project');
  const [hostCatalogType, setHostCatalogType] = useState('static');
  const [targetType, setTargetType] = useState('tcp');
  const [targetPort, setTargetPort] = useState('22');
  const [hostAddress, setHostAddress] = useState('192.168.1.100');
  const [authMethod, setAuthMethod] = useState('password');
  const [workerCount, setWorkerCount] = useState('1');
  const [output, setOutput] = useState('');

  const generate = () => {
    const authBlock = authMethod === 'password'
      ? `resource "boundary_auth_method_password" "password" {
  scope_id = boundary_scope.org.id
  name     = "password-auth"
}`
      : authMethod === 'oidc'
      ? `resource "boundary_auth_method_oidc" "oidc" {
  scope_id             = boundary_scope.org.id
  name                 = "oidc-auth"
  issuer               = "https://auth.example.com"
  client_id            = "boundary-client"
  client_secret        = var.oidc_client_secret
  signing_algorithms   = ["RS256"]
  api_url_prefix       = "https://boundary.example.com"
  claims_scopes        = ["openid", "profile", "email"]
}`
      : `resource "boundary_auth_method_ldap" "ldap" {
  scope_id   = boundary_scope.org.id
  name       = "ldap-auth"
  urls       = ["ldap://ldap.example.com"]
  user_dn    = "ou=users,dc=example,dc=com"
  group_dn   = "ou=groups,dc=example,dc=com"
}`;

    const hostCatalogBlock = hostCatalogType === 'static'
      ? `resource "boundary_host_catalog_static" "catalog" {
  scope_id = boundary_scope.project.id
  name     = "static-hosts"
}

resource "boundary_host_static" "host" {
  host_catalog_id = boundary_host_catalog_static.catalog.id
  name            = "target-host"
  address         = "${hostAddress}"
}

resource "boundary_host_set_static" "host_set" {
  host_catalog_id = boundary_host_catalog_static.catalog.id
  name            = "host-set"
  host_ids        = [boundary_host_static.host.id]
}`
      : `resource "boundary_host_catalog_plugin" "aws" {
  scope_id    = boundary_scope.project.id
  name        = "aws-hosts"
  plugin_name = "aws"
  attributes_json = jsonencode({
    "region" = "us-east-1"
  })
  secrets_json = jsonencode({
    "access_key_id"     = var.aws_access_key
    "secret_access_key" = var.aws_secret_key
  })
}

resource "boundary_host_set_plugin" "aws_set" {
  host_catalog_id = boundary_host_catalog_plugin.aws.id
  name            = "aws-host-set"
  attributes_json = jsonencode({
    "filters" = ["tag:boundary=true"]
  })
}`;

    const workerBlock = parseInt(workerCount) > 0
      ? `\nworker {
  name = "worker-1"
  public_addr = "boundary-worker.example.com"
  controllers = ["boundary-controller.example.com"]
  tags {
    type = ["prod", "us-east-1"]
  }
}`
      : '';

    const config = `# Boundary Configuration for ${scopeName}
# Generated by DeWelope Tools

resource "boundary_scope" "global" {
  global_scope = true
  scope_id     = "global"
}

resource "boundary_scope" "org" {
  scope_id    = boundary_scope.global.id
  name        = "${scopeName}"
  description = "Organization scope for ${scopeName}"
}

resource "boundary_scope" "project" {
  scope_id    = boundary_scope.org.id
  name        = "${projectName}"
  description = "Project scope for ${projectName}"
}

${authBlock}

${hostCatalogBlock}

resource "boundary_target" "target" {
  scope_id     = boundary_scope.project.id
  name         = "${targetType}-target"
  type         = "${targetType}"
  default_port = ${targetPort}
  host_source_ids = [
    ${hostCatalogType === 'static' ? 'boundary_host_set_static.host_set.id' : 'boundary_host_set_plugin.aws_set.id'}
  ]
  session_max_seconds       = 28800
  session_connection_limit  = -1
}${workerBlock}`;

    setOutput(config);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-scope`} className="block text-sm font-medium text-gray-700 mb-1">Organization Name</label>
            <input id={`${toolId}-scope`} type="text" value={scopeName} onChange={(e) => setScopeName(e.target.value)} className="input-field" aria-label={`Organization name for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-project`} className="block text-sm font-medium text-gray-700 mb-1">Project Name</label>
            <input id={`${toolId}-project`} type="text" value={projectName} onChange={(e) => setProjectName(e.target.value)} className="input-field" aria-label="Project name" />
          </div>
          <div>
            <label htmlFor={`${toolId}-catalog`} className="block text-sm font-medium text-gray-700 mb-1">Host Catalog Type</label>
            <select id={`${toolId}-catalog`} value={hostCatalogType} onChange={(e) => setHostCatalogType(e.target.value)} className="input-field" aria-label="Host catalog type">
              <option value="static">Static</option>
              <option value="plugin">Plugin (AWS)</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-target`} className="block text-sm font-medium text-gray-700 mb-1">Target Type</label>
            <select id={`${toolId}-target`} value={targetType} onChange={(e) => setTargetType(e.target.value)} className="input-field" aria-label="Target type">
              <option value="tcp">TCP</option>
              <option value="ssh">SSH</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Target Port</label>
            <input id={`${toolId}-port`} type="number" value={targetPort} onChange={(e) => setTargetPort(e.target.value)} className="input-field" aria-label="Target port" />
          </div>
          <div>
            <label htmlFor={`${toolId}-host`} className="block text-sm font-medium text-gray-700 mb-1">Host Address</label>
            <input id={`${toolId}-host`} type="text" value={hostAddress} onChange={(e) => setHostAddress(e.target.value)} className="input-field" aria-label="Host address" />
          </div>
          <div>
            <label htmlFor={`${toolId}-auth`} className="block text-sm font-medium text-gray-700 mb-1">Auth Method</label>
            <select id={`${toolId}-auth`} value={authMethod} onChange={(e) => setAuthMethod(e.target.value)} className="input-field" aria-label="Auth method">
              <option value="password">Password</option>
              <option value="oidc">OIDC</option>
              <option value="ldap">LDAP</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-workers`} className="block text-sm font-medium text-gray-700 mb-1">Worker Count</label>
            <input id={`${toolId}-workers`} type="number" value={workerCount} onChange={(e) => setWorkerCount(e.target.value)} className="input-field" aria-label="Worker count" />
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Boundary Config</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Boundary Configuration (Terraform)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded border overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
