'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * ChefRecipeGenerator - Generate Chef recipe from resource definitions.
 * Converts user-defined resource parameters into a Chef recipe (Ruby DSL).
 */
export default function ChefRecipeGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [cookbookName, setCookbookName] = useState('my_cookbook');
  const [recipeName, setRecipeName] = useState('default');
  const [resources, setResources] = useState([
    { type: 'package', name: 'nginx', action: 'install', properties: '' },
  ]);
  const [output, setOutput] = useState('');

  const addResource = () => {
    setResources([...resources, { type: 'package', name: '', action: 'install', properties: '' }]);
  };

  const removeResource = (index: number) => {
    setResources(resources.filter((_, i) => i !== index));
  };

  const updateResource = (index: number, field: string, value: string) => {
    const updated = [...resources];
    updated[index] = { ...updated[index], [field]: value };
    setResources(updated);
  };

  const generate = () => {
    const lines: string[] = [];
    lines.push(`# Cookbook:: ${cookbookName}`);
    lines.push(`# Recipe:: ${recipeName}`);
    lines.push(`#`);
    lines.push(`# Generated by DeWelope Tools`);
    lines.push('');

    resources.forEach((res) => {
      if (!res.name) return;
      lines.push(`${res.type} '${res.name}' do`);
      lines.push(`  action :${res.action}`);
      if (res.properties.trim()) {
        res.properties.split('\n').forEach((prop) => {
          const trimmed = prop.trim();
          if (trimmed) lines.push(`  ${trimmed}`);
        });
      }
      lines.push('end');
      lines.push('');
    });

    setOutput(lines.join('\n'));
  };

  const resourceTypes = ['package', 'service', 'template', 'file', 'directory', 'execute', 'user', 'group', 'cron', 'remote_file'];
  const actions: Record<string, string[]> = {
    package: ['install', 'remove', 'upgrade', 'purge'],
    service: ['start', 'stop', 'restart', 'enable', 'disable'],
    template: ['create', 'delete'],
    file: ['create', 'delete', 'touch'],
    directory: ['create', 'delete'],
    execute: ['run', 'nothing'],
    user: ['create', 'remove', 'modify', 'manage', 'lock', 'unlock'],
    group: ['create', 'remove', 'modify', 'manage'],
    cron: ['create', 'delete'],
    remote_file: ['create', 'delete'],
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div>
            <label htmlFor={`${toolId}-cookbook`} className="block text-sm font-medium text-gray-700 mb-1">
              Cookbook Name
            </label>
            <input
              id={`${toolId}-cookbook`}
              type="text"
              value={cookbookName}
              onChange={(e) => setCookbookName(e.target.value)}
              className="input-field"
              aria-label={`Cookbook name for ${toolName}`}
            />
          </div>
          <div>
            <label htmlFor={`${toolId}-recipe`} className="block text-sm font-medium text-gray-700 mb-1">
              Recipe Name
            </label>
            <input
              id={`${toolId}-recipe`}
              type="text"
              value={recipeName}
              onChange={(e) => setRecipeName(e.target.value)}
              className="input-field"
              aria-label="Recipe name"
            />
          </div>
        </div>

        <div className="space-y-3">
          <label className="block text-sm font-medium text-gray-700">Resources</label>
          {resources.map((res, idx) => (
            <div key={idx} className="border border-gray-200 rounded-lg p-3 space-y-2">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                <select
                  value={res.type}
                  onChange={(e) => updateResource(idx, 'type', e.target.value)}
                  className="input-field"
                  aria-label="Resource type"
                >
                  {resourceTypes.map((t) => (
                    <option key={t} value={t}>{t}</option>
                  ))}
                </select>
                <input
                  type="text"
                  value={res.name}
                  onChange={(e) => updateResource(idx, 'name', e.target.value)}
                  placeholder="Resource name"
                  className="input-field"
                  aria-label="Resource name"
                />
                <select
                  value={res.action}
                  onChange={(e) => updateResource(idx, 'action', e.target.value)}
                  className="input-field"
                  aria-label="Resource action"
                >
                  {(actions[res.type] || ['create', 'delete']).map((a) => (
                    <option key={a} value={a}>{a}</option>
                  ))}
                </select>
              </div>
              <textarea
                value={res.properties}
                onChange={(e) => updateResource(idx, 'properties', e.target.value)}
                placeholder="Additional properties (one per line, e.g. source 'nginx.conf.erb')"
                className="input-field h-16 resize-y font-mono text-sm"
                aria-label="Resource properties"
              />
              <button
                onClick={() => removeResource(idx)}
                className="text-sm text-red-600 hover:text-red-800"
              >
                Remove
              </button>
            </div>
          ))}
          <button
            onClick={addResource}
            className="text-sm text-blue-600 hover:text-blue-800 font-medium"
          >
            + Add Resource
          </button>
        </div>

        <button
          onClick={generate}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          Generate Recipe
        </button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated Chef Recipe</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
