'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * CiliumNetworkPolicyGenerator - Generate Cilium network policy YAML
 * with configurable endpoints, ports, and protocol rules.
 */
export default function CiliumNetworkPolicyGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [policyName, setPolicyName] = useState('allow-http');
  const [namespace, setNamespace] = useState('default');
  const [endpointLabel, setEndpointLabel] = useState('app=backend');
  const [ingressFrom, setIngressFrom] = useState('app=frontend');
  const [port, setPort] = useState('80');
  const [protocol, setProtocol] = useState('TCP');
  const [output, setOutput] = useState('');

  const generate = () => {
    const portNum = parseInt(port, 10) || 80;
    const [endKey, endVal] = endpointLabel.includes('=') ? endpointLabel.split('=') : ['app', endpointLabel];
    const [fromKey, fromVal] = ingressFrom.includes('=') ? ingressFrom.split('=') : ['app', ingressFrom];

    const yaml = `apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "${policyName}"
  namespace: "${namespace}"
spec:
  description: "Policy generated by DeWelope Tools"
  endpointSelector:
    matchLabels:
      ${endKey}: ${endVal}
  ingress:
  - fromEndpoints:
    - matchLabels:
        ${fromKey}: ${fromVal}
    toPorts:
    - ports:
      - port: "${portNum}"
        protocol: ${protocol}
  egress:
  - toEndpoints:
    - matchLabels:
        ${fromKey}: ${fromVal}
    toPorts:
    - ports:
      - port: "${portNum}"
        protocol: ${protocol}`;

    setOutput(yaml);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-name`} className="block text-sm font-medium text-gray-700 mb-1">Policy Name</label>
            <input id={`${toolId}-name`} type="text" value={policyName} onChange={(e) => setPolicyName(e.target.value)} placeholder="allow-http" aria-label={`Policy name for ${toolName}`} className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-ns`} className="block text-sm font-medium text-gray-700 mb-1">Namespace</label>
            <input id={`${toolId}-ns`} type="text" value={namespace} onChange={(e) => setNamespace(e.target.value)} placeholder="default" aria-label="Namespace" className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-endpoint`} className="block text-sm font-medium text-gray-700 mb-1">Endpoint Label (key=value)</label>
            <input id={`${toolId}-endpoint`} type="text" value={endpointLabel} onChange={(e) => setEndpointLabel(e.target.value)} placeholder="app=backend" aria-label="Endpoint label" className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-from`} className="block text-sm font-medium text-gray-700 mb-1">Ingress From Label (key=value)</label>
            <input id={`${toolId}-from`} type="text" value={ingressFrom} onChange={(e) => setIngressFrom(e.target.value)} placeholder="app=frontend" aria-label="Ingress from label" className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port</label>
            <input id={`${toolId}-port`} type="number" min="1" max="65535" value={port} onChange={(e) => setPort(e.target.value)} aria-label="Port number" className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-proto`} className="block text-sm font-medium text-gray-700 mb-1">Protocol</label>
            <select id={`${toolId}-proto`} value={protocol} onChange={(e) => setProtocol(e.target.value)} aria-label="Protocol" className="input-field">
              <option value="TCP">TCP</option>
              <option value="UDP">UDP</option>
              <option value="ANY">ANY</option>
            </select>
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Policy</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Cilium Network Policy YAML</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-4 rounded-lg">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
