'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * DoxygenConfigGenerator - Generate Doxygen Doxyfile configuration files.
 */
export default function DoxygenConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [projectName, setProjectName] = useState('MyProject');
  const [projectVersion, setProjectVersion] = useState('1.0.0');
  const [inputDir, setInputDir] = useState('./src');
  const [outputDir, setOutputDir] = useState('./docs');
  const [recursive, setRecursive] = useState(true);
  const [extractAll, setExtractAll] = useState(true);
  const [generateHtml, setGenerateHtml] = useState(true);
  const [generateLatex, setGenerateLatex] = useState(false);
  const [language, setLanguage] = useState('C++');
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines = [
      '# Doxyfile configuration generated by DeWelope Tools',
      '',
      '# Project settings',
      `PROJECT_NAME           = "${projectName}"`,
      `PROJECT_NUMBER         = "${projectVersion}"`,
      `OUTPUT_DIRECTORY       = ${outputDir}`,
      '',
      '# Input settings',
      `INPUT                  = ${inputDir}`,
      `RECURSIVE              = ${recursive ? 'YES' : 'NO'}`,
      `FILE_PATTERNS          = ${getFilePatterns(language)}`,
      '',
      '# Extraction settings',
      `EXTRACT_ALL            = ${extractAll ? 'YES' : 'NO'}`,
      'EXTRACT_PRIVATE        = NO',
      'EXTRACT_STATIC         = YES',
      '',
      '# Output formats',
      `GENERATE_HTML          = ${generateHtml ? 'YES' : 'NO'}`,
      `GENERATE_LATEX         = ${generateLatex ? 'YES' : 'NO'}`,
      '',
      '# Source browsing',
      'SOURCE_BROWSER         = YES',
      'INLINE_SOURCES         = NO',
      '',
      '# Graphs',
      'HAVE_DOT               = NO',
      'CLASS_DIAGRAMS         = YES',
      '',
      '# Warnings',
      'WARNINGS               = YES',
      'WARN_IF_UNDOCUMENTED   = YES',
      'WARN_IF_DOC_ERROR      = YES',
    ];

    setOutput(lines.join('\n'));
  };

  const getFilePatterns = (lang: string): string => {
    switch (lang) {
      case 'C++': return '*.cpp *.h *.hpp *.c';
      case 'C': return '*.c *.h';
      case 'Java': return '*.java';
      case 'Python': return '*.py';
      case 'C#': return '*.cs';
      default: return '*.cpp *.h *.hpp *.c';
    }
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-name`} className="block text-sm font-medium text-gray-700 mb-1">
                Project Name
              </label>
              <input
                id={`${toolId}-name`}
                type="text"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                className="input-field"
                aria-label={`Project name for ${toolName}`}
              />
            </div>
            <div>
              <label htmlFor={`${toolId}-version`} className="block text-sm font-medium text-gray-700 mb-1">
                Project Version
              </label>
              <input
                id={`${toolId}-version`}
                type="text"
                value={projectVersion}
                onChange={(e) => setProjectVersion(e.target.value)}
                className="input-field"
                aria-label="Project version"
              />
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-input`} className="block text-sm font-medium text-gray-700 mb-1">
                Input Directory
              </label>
              <input
                id={`${toolId}-input`}
                type="text"
                value={inputDir}
                onChange={(e) => setInputDir(e.target.value)}
                className="input-field"
                aria-label="Input directory"
              />
            </div>
            <div>
              <label htmlFor={`${toolId}-output`} className="block text-sm font-medium text-gray-700 mb-1">
                Output Directory
              </label>
              <input
                id={`${toolId}-output`}
                type="text"
                value={outputDir}
                onChange={(e) => setOutputDir(e.target.value)}
                className="input-field"
                aria-label="Output directory"
              />
            </div>
          </div>
          <div>
            <label htmlFor={`${toolId}-lang`} className="block text-sm font-medium text-gray-700 mb-1">
              Language
            </label>
            <select
              id={`${toolId}-lang`}
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              className="input-field"
              aria-label="Programming language"
            >
              <option value="C++">C++</option>
              <option value="C">C</option>
              <option value="Java">Java</option>
              <option value="Python">Python</option>
              <option value="C#">C#</option>
            </select>
          </div>
          <div className="flex flex-wrap items-center gap-4">
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={recursive} onChange={(e) => setRecursive(e.target.checked)} />
              Recursive
            </label>
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={extractAll} onChange={(e) => setExtractAll(e.target.checked)} />
              Extract All
            </label>
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={generateHtml} onChange={(e) => setGenerateHtml(e.target.checked)} />
              Generate HTML
            </label>
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={generateLatex} onChange={(e) => setGenerateLatex(e.target.checked)} />
              Generate LaTeX
            </label>
          </div>
          <button onClick={generate} className="btn-primary" aria-label="Generate Doxyfile">
            Generate Doxyfile
          </button>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated Doxyfile</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
