'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * Fail2banConfigGenerator - Generate Fail2Ban jail configuration files.
 * Supports common services like SSH, Apache, Nginx, and custom jails.
 */
export default function Fail2banConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [jailName, setJailName] = useState('sshd');
  const [enabled, setEnabled] = useState(true);
  const [port, setPort] = useState('ssh');
  const [filter, setFilter] = useState('sshd');
  const [logPath, setLogPath] = useState('/var/log/auth.log');
  const [maxRetry, setMaxRetry] = useState('5');
  const [findTime, setFindTime] = useState('600');
  const [banTime, setBanTime] = useState('3600');
  const [banAction, setBanAction] = useState('iptables-multiport');
  const [ignoreIp, setIgnoreIp] = useState('127.0.0.1/8');
  const [jails, setJails] = useState<string[]>([]);
  const [output, setOutput] = useState('');

  const addJail = () => {
    let jail = `[${jailName}]\n`;
    jail += `enabled = ${enabled ? 'true' : 'false'}\n`;
    jail += `port = ${port}\n`;
    jail += `filter = ${filter}\n`;
    jail += `logpath = ${logPath}\n`;
    jail += `maxretry = ${maxRetry}\n`;
    jail += `findtime = ${findTime}\n`;
    jail += `bantime = ${banTime}\n`;
    jail += `banaction = ${banAction}\n`;
    if (ignoreIp.trim()) jail += `ignoreip = ${ignoreIp}\n`;

    const newJails = [...jails, jail];
    setJails(newJails);
    generateOutput(newJails);
  };

  const addPreset = (preset: string) => {
    let jail = '';
    switch (preset) {
      case 'sshd':
        jail = `[sshd]\nenabled = true\nport = ssh\nfilter = sshd\nlogpath = /var/log/auth.log\nmaxretry = 3\nfindtime = 600\nbantime = 3600\nbanaction = iptables-multiport\n`;
        break;
      case 'apache':
        jail = `[apache-auth]\nenabled = true\nport = http,https\nfilter = apache-auth\nlogpath = /var/log/apache2/error.log\nmaxretry = 5\nfindtime = 600\nbantime = 3600\nbanaction = iptables-multiport\n`;
        break;
      case 'nginx':
        jail = `[nginx-http-auth]\nenabled = true\nport = http,https\nfilter = nginx-http-auth\nlogpath = /var/log/nginx/error.log\nmaxretry = 5\nfindtime = 600\nbantime = 3600\nbanaction = iptables-multiport\n`;
        break;
      case 'postfix':
        jail = `[postfix]\nenabled = true\nport = smtp,465,submission\nfilter = postfix\nlogpath = /var/log/mail.log\nmaxretry = 5\nfindtime = 600\nbantime = 3600\nbanaction = iptables-multiport\n`;
        break;
      default:
        return;
    }
    const newJails = [...jails, jail];
    setJails(newJails);
    generateOutput(newJails);
  };

  const generateOutput = (jailList: string[]) => {
    let result = '# Fail2Ban Jail Configuration\n';
    result += '# Generated by DeWelope Tools\n';
    result += '# Place in /etc/fail2ban/jail.local\n\n';
    result += '[DEFAULT]\n';
    result += `bantime = ${banTime}\n`;
    result += `findtime = ${findTime}\n`;
    result += `maxretry = ${maxRetry}\n`;
    result += `banaction = ${banAction}\n`;
    if (ignoreIp.trim()) result += `ignoreip = ${ignoreIp}\n`;
    result += '\n';
    jailList.forEach(jail => {
      result += `${jail}\n`;
    });

    setOutput(result);
  };

  const clearJails = () => {
    setJails([]);
    setOutput('');
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="flex gap-2 flex-wrap">
            <button onClick={() => addPreset('sshd')} className="btn-secondary text-xs">+ SSH Jail</button>
            <button onClick={() => addPreset('apache')} className="btn-secondary text-xs">+ Apache</button>
            <button onClick={() => addPreset('nginx')} className="btn-secondary text-xs">+ Nginx</button>
            <button onClick={() => addPreset('postfix')} className="btn-secondary text-xs">+ Postfix</button>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-name`} className="block text-sm font-medium text-gray-700 mb-1">Jail Name</label>
              <input id={`${toolId}-name`} type="text" value={jailName} onChange={(e) => setJailName(e.target.value)} placeholder="sshd" className="input-field" aria-label={`Jail name for ${toolName}`} />
            </div>
            <div>
              <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port</label>
              <input id={`${toolId}-port`} type="text" value={port} onChange={(e) => setPort(e.target.value)} placeholder="ssh, http, 8080" className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-filter`} className="block text-sm font-medium text-gray-700 mb-1">Filter</label>
              <input id={`${toolId}-filter`} type="text" value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="sshd" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-logpath`} className="block text-sm font-medium text-gray-700 mb-1">Log Path</label>
              <input id={`${toolId}-logpath`} type="text" value={logPath} onChange={(e) => setLogPath(e.target.value)} placeholder="/var/log/auth.log" className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label htmlFor={`${toolId}-maxretry`} className="block text-sm font-medium text-gray-700 mb-1">Max Retry</label>
              <input id={`${toolId}-maxretry`} type="number" min="1" value={maxRetry} onChange={(e) => setMaxRetry(e.target.value)} className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-findtime`} className="block text-sm font-medium text-gray-700 mb-1">Find Time (s)</label>
              <input id={`${toolId}-findtime`} type="number" min="60" value={findTime} onChange={(e) => setFindTime(e.target.value)} className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-bantime`} className="block text-sm font-medium text-gray-700 mb-1">Ban Time (s)</label>
              <input id={`${toolId}-bantime`} type="number" min="60" value={banTime} onChange={(e) => setBanTime(e.target.value)} className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-banaction`} className="block text-sm font-medium text-gray-700 mb-1">Ban Action</label>
              <select id={`${toolId}-banaction`} value={banAction} onChange={(e) => setBanAction(e.target.value)} className="input-field">
                <option value="iptables-multiport">iptables-multiport</option>
                <option value="iptables-allports">iptables-allports</option>
                <option value="firewallcmd-ipset">firewallcmd-ipset</option>
                <option value="ufw">ufw</option>
                <option value="nftables-multiport">nftables-multiport</option>
              </select>
            </div>
            <div>
              <label htmlFor={`${toolId}-ignoreip`} className="block text-sm font-medium text-gray-700 mb-1">Ignore IPs</label>
              <input id={`${toolId}-ignoreip`} type="text" value={ignoreIp} onChange={(e) => setIgnoreIp(e.target.value)} placeholder="127.0.0.1/8 ::1" className="input-field" />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <input type="checkbox" id={`${toolId}-enabled`} checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />
            <label htmlFor={`${toolId}-enabled`} className="text-sm text-gray-700">Enabled</label>
          </div>
          <div className="flex gap-2">
            <button onClick={addJail} className="btn-primary">Add Jail</button>
            <button onClick={clearJails} className="btn-secondary">Clear All</button>
          </div>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Fail2Ban Configuration ({jails.length} jails)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-3 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
