'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * HaproxyConfigGenerator - Generate HAProxy frontend/backend configuration.
 */
export default function HaproxyConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [frontendName, setFrontendName] = useState('http_front');
  const [frontendPort, setFrontendPort] = useState('80');
  const [backendName, setBackendName] = useState('app_backend');
  const [algorithm, setAlgorithm] = useState<'roundrobin' | 'leastconn' | 'source'>('roundrobin');
  const [servers, setServers] = useState('server1 192.168.1.10:8080\nserver2 192.168.1.11:8080');
  const [enableHealthCheck, setEnableHealthCheck] = useState(true);
  const [enableStats, setEnableStats] = useState(true);
  const [mode, setMode] = useState<'http' | 'tcp'>('http');
  const [output, setOutput] = useState('');

  const generate = () => {
    const serverLines = servers.split('\n').filter((s) => s.trim()).map((s) => {
      const parts = s.trim().split(/\s+/);
      const name = parts[0] || 'server1';
      const addr = parts[1] || '127.0.0.1:8080';
      const check = enableHealthCheck ? ' check' : '';
      return `  server ${name} ${addr}${check}`;
    });

    let config = `# HAProxy Configuration\n# Generated by DeWelope Tools\n\n`;

    config += `global\n  log /dev/log local0\n  maxconn 4096\n  daemon\n\n`;

    config += `defaults\n  mode ${mode}\n  log global\n  option ${mode === 'http' ? 'httplog' : 'tcplog'}\n  option dontlognull\n  timeout connect 5000ms\n  timeout client 50000ms\n  timeout server 50000ms\n  retries 3\n\n`;

    config += `frontend ${frontendName}\n  bind *:${frontendPort}\n  mode ${mode}\n`;
    if (mode === 'http') {
      config += `  option forwardfor\n  http-request set-header X-Forwarded-Proto http\n`;
    }
    config += `  default_backend ${backendName}\n\n`;

    config += `backend ${backendName}\n  mode ${mode}\n  balance ${algorithm}\n`;
    if (mode === 'http' && enableHealthCheck) {
      config += `  option httpchk GET /health\n`;
    }
    config += serverLines.join('\n') + '\n';

    if (enableStats) {
      config += `\nlisten stats\n  bind *:8404\n  mode http\n  stats enable\n  stats uri /stats\n  stats refresh 10s\n  stats admin if LOCALHOST\n`;
    }

    setOutput(config);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-frontend`} className="block text-sm font-medium text-gray-700 mb-1">Frontend Name</label>
              <input id={`${toolId}-frontend`} type="text" value={frontendName} onChange={(e) => setFrontendName(e.target.value)} aria-label={`Frontend name for ${toolName}`} className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Listen Port</label>
              <input id={`${toolId}-port`} type="text" value={frontendPort} onChange={(e) => setFrontendPort(e.target.value)} aria-label="Listen port" className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-backend`} className="block text-sm font-medium text-gray-700 mb-1">Backend Name</label>
              <input id={`${toolId}-backend`} type="text" value={backendName} onChange={(e) => setBackendName(e.target.value)} aria-label="Backend name" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-mode`} className="block text-sm font-medium text-gray-700 mb-1">Mode</label>
              <select id={`${toolId}-mode`} value={mode} onChange={(e) => setMode(e.target.value as 'http' | 'tcp')} aria-label="Mode" className="input-field">
                <option value="http">HTTP</option>
                <option value="tcp">TCP</option>
              </select>
            </div>
          </div>
          <div>
            <label htmlFor={`${toolId}-algo`} className="block text-sm font-medium text-gray-700 mb-1">Balance Algorithm</label>
            <select id={`${toolId}-algo`} value={algorithm} onChange={(e) => setAlgorithm(e.target.value as typeof algorithm)} aria-label="Balance algorithm" className="input-field">
              <option value="roundrobin">Round Robin</option>
              <option value="leastconn">Least Connections</option>
              <option value="source">Source IP</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-servers`} className="block text-sm font-medium text-gray-700 mb-1">Backend Servers (name address:port, one per line)</label>
            <textarea id={`${toolId}-servers`} value={servers} onChange={(e) => setServers(e.target.value)} aria-label="Backend servers" className="input-field h-24 resize-y font-mono" placeholder="server1 192.168.1.10:8080" />
          </div>
          <div className="flex gap-4">
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input type="checkbox" checked={enableHealthCheck} onChange={(e) => setEnableHealthCheck(e.target.checked)} className="rounded" />
              Health Checks
            </label>
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input type="checkbox" checked={enableStats} onChange={(e) => setEnableStats(e.target.checked)} className="rounded" />
              Stats Page
            </label>
          </div>
        </div>
      </InputArea>

      <button onClick={generate} className="btn-primary" aria-label="Generate HAProxy config">Generate HAProxy Config</button>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">HAProxy Configuration</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg border border-gray-200 overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
