'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * IptablesRuleGenerator - Generate iptables firewall rules for Linux systems.
 * Supports common scenarios like allowing/blocking ports, IPs, and protocols.
 */
export default function IptablesRuleGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [chain, setChain] = useState('INPUT');
  const [action, setAction] = useState('ACCEPT');
  const [protocol, setProtocol] = useState('tcp');
  const [port, setPort] = useState('');
  const [sourceIp, setSourceIp] = useState('');
  const [destIp, setDestIp] = useState('');
  const [iface, setIface] = useState('');
  const [state, setState] = useState('');
  const [comment, setComment] = useState('');
  const [rules, setRules] = useState<string[]>([]);
  const [output, setOutput] = useState('');

  const addRule = () => {
    const parts: string[] = ['iptables'];
    parts.push(`-A ${chain}`);

    if (protocol) parts.push(`-p ${protocol}`);
    if (sourceIp.trim()) parts.push(`-s ${sourceIp.trim()}`);
    if (destIp.trim()) parts.push(`-d ${destIp.trim()}`);
    if (iface.trim()) parts.push(`-i ${iface.trim()}`);
    if (port.trim()) parts.push(`--dport ${port.trim()}`);
    if (state) parts.push(`-m state --state ${state}`);
    if (comment.trim()) parts.push(`-m comment --comment "${comment.trim()}"`);
    parts.push(`-j ${action}`);

    const rule = parts.join(' ');
    const newRules = [...rules, rule];
    setRules(newRules);
    generateOutput(newRules);
  };

  const generateOutput = (ruleList: string[]) => {
    let result = '#!/bin/bash\n';
    result += '# iptables Firewall Rules\n';
    result += '# Generated by DeWelope Tools\n\n';
    result += '# Flush existing rules\n';
    result += 'iptables -F\n';
    result += 'iptables -X\n\n';
    result += '# Set default policies\n';
    result += 'iptables -P INPUT DROP\n';
    result += 'iptables -P FORWARD DROP\n';
    result += 'iptables -P OUTPUT ACCEPT\n\n';
    result += '# Allow loopback\n';
    result += 'iptables -A INPUT -i lo -j ACCEPT\n';
    result += 'iptables -A OUTPUT -o lo -j ACCEPT\n\n';
    result += '# Allow established connections\n';
    result += 'iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT\n\n';
    result += '# Custom rules\n';
    ruleList.forEach(rule => {
      result += `${rule}\n`;
    });
    result += '\n# Save rules\n';
    result += '# Debian/Ubuntu: iptables-save > /etc/iptables/rules.v4\n';
    result += '# CentOS/RHEL: service iptables save\n';

    setOutput(result);
  };

  const addPreset = (preset: string) => {
    let newRules: string[] = [];
    switch (preset) {
      case 'ssh':
        newRules = [...rules, 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT'];
        break;
      case 'web':
        newRules = [...rules, 'iptables -A INPUT -p tcp --dport 80 -j ACCEPT', 'iptables -A INPUT -p tcp --dport 443 -j ACCEPT'];
        break;
      case 'dns':
        newRules = [...rules, 'iptables -A INPUT -p udp --dport 53 -j ACCEPT', 'iptables -A INPUT -p tcp --dport 53 -j ACCEPT'];
        break;
      case 'ping':
        newRules = [...rules, 'iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT'];
        break;
      default:
        return;
    }
    setRules(newRules);
    generateOutput(newRules);
  };

  const clearRules = () => {
    setRules([]);
    setOutput('');
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="flex gap-2 flex-wrap">
            <button onClick={() => addPreset('ssh')} className="btn-secondary text-xs">+ SSH (22)</button>
            <button onClick={() => addPreset('web')} className="btn-secondary text-xs">+ HTTP/HTTPS (80,443)</button>
            <button onClick={() => addPreset('dns')} className="btn-secondary text-xs">+ DNS (53)</button>
            <button onClick={() => addPreset('ping')} className="btn-secondary text-xs">+ Ping</button>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-chain`} className="block text-sm font-medium text-gray-700 mb-1">Chain</label>
              <select id={`${toolId}-chain`} value={chain} onChange={(e) => setChain(e.target.value)} className="input-field">
                <option value="INPUT">INPUT</option>
                <option value="OUTPUT">OUTPUT</option>
                <option value="FORWARD">FORWARD</option>
              </select>
            </div>
            <div>
              <label htmlFor={`${toolId}-action`} className="block text-sm font-medium text-gray-700 mb-1">Action</label>
              <select id={`${toolId}-action`} value={action} onChange={(e) => setAction(e.target.value)} className="input-field">
                <option value="ACCEPT">ACCEPT</option>
                <option value="DROP">DROP</option>
                <option value="REJECT">REJECT</option>
                <option value="LOG">LOG</option>
              </select>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-protocol`} className="block text-sm font-medium text-gray-700 mb-1">Protocol</label>
              <select id={`${toolId}-protocol`} value={protocol} onChange={(e) => setProtocol(e.target.value)} className="input-field">
                <option value="tcp">TCP</option>
                <option value="udp">UDP</option>
                <option value="icmp">ICMP</option>
                <option value="all">All</option>
              </select>
            </div>
            <div>
              <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port</label>
              <input id={`${toolId}-port`} type="text" value={port} onChange={(e) => setPort(e.target.value)} placeholder="80, 443, 8000:9000" className="input-field" aria-label={`Port for ${toolName}`} />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-source`} className="block text-sm font-medium text-gray-700 mb-1">Source IP</label>
              <input id={`${toolId}-source`} type="text" value={sourceIp} onChange={(e) => setSourceIp(e.target.value)} placeholder="192.168.1.0/24" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-dest`} className="block text-sm font-medium text-gray-700 mb-1">Destination IP</label>
              <input id={`${toolId}-dest`} type="text" value={destIp} onChange={(e) => setDestIp(e.target.value)} placeholder="10.0.0.1" className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-iface`} className="block text-sm font-medium text-gray-700 mb-1">Interface</label>
              <input id={`${toolId}-iface`} type="text" value={iface} onChange={(e) => setIface(e.target.value)} placeholder="eth0" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-state`} className="block text-sm font-medium text-gray-700 mb-1">Connection State</label>
              <select id={`${toolId}-state`} value={state} onChange={(e) => setState(e.target.value)} className="input-field">
                <option value="">None</option>
                <option value="NEW">NEW</option>
                <option value="ESTABLISHED">ESTABLISHED</option>
                <option value="RELATED">RELATED</option>
                <option value="NEW,ESTABLISHED">NEW,ESTABLISHED</option>
              </select>
            </div>
          </div>
          <div>
            <label htmlFor={`${toolId}-comment`} className="block text-sm font-medium text-gray-700 mb-1">Comment</label>
            <input id={`${toolId}-comment`} type="text" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Allow web traffic" className="input-field" />
          </div>
          <div className="flex gap-2">
            <button onClick={addRule} className="btn-primary">Add Rule</button>
            <button onClick={clearRules} className="btn-secondary">Clear All</button>
          </div>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated iptables Script ({rules.length} custom rules)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-3 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
