'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * JsonToGoStruct - Convert JSON to Go struct definitions.
 * Handles nested objects, arrays, and infers Go types from JSON values.
 */
export default function JsonToGoStruct({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [input, setInput] = useState('');
  const [structName, setStructName] = useState('AutoGenerated');
  const [output, setOutput] = useState('');
  const [errors, setErrors] = useState<Record<string, string>>({});

  const capitalize = (s: string): string => {
    return s.replace(/(?:^|[_\-\s])(\w)/g, (_, c) => c.toUpperCase());
  };

  const goType = (value: unknown, key: string, structs: string[]): string => {
    if (value === null) return 'interface{}';
    if (Array.isArray(value)) {
      if (value.length === 0) return '[]interface{}';
      return '[]' + goType(value[0], key, structs);
    }
    switch (typeof value) {
      case 'string': return 'string';
      case 'number': return Number.isInteger(value) ? 'int64' : 'float64';
      case 'boolean': return 'bool';
      case 'object': {
        const nestedName = capitalize(key);
        const nested = generateStruct(nestedName, value as Record<string, unknown>, structs);
        structs.push(nested);
        return nestedName;
      }
      default: return 'interface{}';
    }
  };

  const generateStruct = (name: string, obj: Record<string, unknown>, structs: string[]): string => {
    const fields = Object.entries(obj).map(([key, value]) => {
      const fieldName = capitalize(key);
      const fieldType = goType(value, key, structs);
      const jsonTag = `\`json:"${key}"\``;
      return `\t${fieldName} ${fieldType} ${jsonTag}`;
    });

    return `type ${name} struct {\n${fields.join('\n')}\n}`;
  };

  const convert = () => {
    const newErrors: Record<string, string> = {};

    if (!input.trim()) {
      newErrors.input = 'Please enter JSON to convert';
      setErrors(newErrors);
      setOutput('');
      return;
    }

    try {
      const parsed = JSON.parse(input);
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        newErrors.input = 'Input must be a JSON object (not array or primitive)';
        setErrors(newErrors);
        setOutput('');
        return;
      }

      const structs: string[] = [];
      const mainStruct = generateStruct(structName || 'AutoGenerated', parsed, structs);
      const allStructs = [...structs, mainStruct].join('\n\n');
      setErrors({});
      setOutput(allStructs);
    } catch {
      newErrors.input = 'Invalid JSON. Please check your input.';
      setErrors(newErrors);
      setOutput('');
    }
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <label htmlFor={`${toolId}-name`} className="block text-sm font-medium text-gray-700 mb-1">
          Struct Name
        </label>
        <input
          id={`${toolId}-name`}
          type="text"
          value={structName}
          onChange={(e) => setStructName(e.target.value)}
          placeholder="e.g. User"
          aria-label={`Struct name for ${toolName}`}
          className="input-field"
        />
      </InputArea>

      <InputArea error={errors.input}>
        <label htmlFor={`${toolId}-input`} className="block text-sm font-medium text-gray-700 mb-1">
          JSON Input
        </label>
        <textarea
          id={`${toolId}-input`}
          value={input}
          onChange={(e) => {
            setInput(e.target.value);
            if (errors.input) setErrors({});
          }}
          placeholder={'{\n  "name": "John",\n  "age": 30,\n  "email": "john@example.com",\n  "active": true\n}'}
          aria-label={`JSON input for ${toolName}`}
          className="input-field h-48 resize-y font-mono"
        />
      </InputArea>

      <button onClick={convert} aria-label="Convert JSON to Go struct" className="btn-primary">
        Convert to Go Struct
      </button>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Go Struct Definition</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg border border-gray-200 overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
