'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

export default function JsonToGoStruct({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');

  const toGoType = (val: unknown): string => {
    if (val === null) return 'interface{}';
    if (typeof val === 'string') return 'string';
    if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float64';
    if (typeof val === 'boolean') return 'bool';
    if (Array.isArray(val)) return val.length > 0 ? `[]${toGoType(val[0])}` : '[]interface{}';
    return 'interface{}';
  };

  const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1).replace(/[_-](\w)/g, (_, c) => c.toUpperCase());

  const convert = () => {
    try {
      const parsed = JSON.parse(input);
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) { setOutput('Error: Input must be a JSON object.'); return; }
      const fields = Object.entries(parsed).map(([key, val]) => {
        const goName = capitalize(key);
        const goType = typeof val === 'object' && val !== null && !Array.isArray(val) ? 'struct{}' : toGoType(val);
        return `\t${goName} ${goType} \`json:"${key}"\``;
      });
      setOutput(`type AutoGenerated struct {\n${fields.join('\n')}\n}`);
    } catch { setOutput('Error: Invalid JSON input.'); }
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <label htmlFor={`${toolId}-input`} className="block text-sm font-medium text-gray-700 mb-1">JSON Input</label>
        <textarea id={`${toolId}-input`} value={input} onChange={(e) => setInput(e.target.value)} placeholder='{"name": "John", "age": 30}' aria-label={`Input for ${toolName}`} className="input-field h-40 resize-y font-mono" />
      </InputArea>
      <button onClick={convert} className="btn-primary">Generate Go Struct</button>
      <OutputArea hasContent={!!output}>
        {output && (<div className="space-y-2"><pre className="whitespace-pre-wrap text-sm font-mono text-gray-800">{output}</pre><CopyToClipboard text={output} /></div>)}
      </OutputArea>
    </div>
  );
}
