'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * KafkaConfigGenerator - Generate Apache Kafka producer/consumer configuration.
 * Supports common settings for producers and consumers with various serialization formats.
 */
export default function KafkaConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [configType, setConfigType] = useState<'producer' | 'consumer'>('producer');
  const [bootstrapServers, setBootstrapServers] = useState('localhost:9092');
  const [groupId, setGroupId] = useState('my-consumer-group');
  const [acks, setAcks] = useState<'all' | '1' | '0'>('all');
  const [serializer, setSerializer] = useState('string');
  const [securityProtocol, setSecurityProtocol] = useState('PLAINTEXT');
  const [batchSize, setBatchSize] = useState('16384');
  const [lingerMs, setLingerMs] = useState('1');
  const [autoOffsetReset, setAutoOffsetReset] = useState('earliest');
  const [enableAutoCommit, setEnableAutoCommit] = useState(true);
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines: string[] = [];
    lines.push(`# Apache Kafka ${configType === 'producer' ? 'Producer' : 'Consumer'} Configuration`);
    lines.push(`# Generated by DeWelope Tools`);
    lines.push('');
    lines.push(`bootstrap.servers=${bootstrapServers}`);
    lines.push(`security.protocol=${securityProtocol}`);
    lines.push('');

    if (configType === 'producer') {
      const serClass = serializer === 'string'
        ? 'org.apache.kafka.common.serialization.StringSerializer'
        : serializer === 'json'
          ? 'io.confluent.kafka.serializers.KafkaJsonSerializer'
          : 'io.confluent.kafka.serializers.KafkaAvroSerializer';
      lines.push(`key.serializer=${serClass}`);
      lines.push(`value.serializer=${serClass}`);
      lines.push(`acks=${acks}`);
      lines.push(`batch.size=${batchSize}`);
      lines.push(`linger.ms=${lingerMs}`);
      lines.push(`buffer.memory=33554432`);
      lines.push(`retries=2147483647`);
      lines.push(`max.in.flight.requests.per.connection=5`);
      lines.push(`enable.idempotence=true`);
      lines.push(`compression.type=snappy`);
    } else {
      const deserClass = serializer === 'string'
        ? 'org.apache.kafka.common.serialization.StringDeserializer'
        : serializer === 'json'
          ? 'io.confluent.kafka.serializers.KafkaJsonDeserializer'
          : 'io.confluent.kafka.serializers.KafkaAvroDeserializer';
      lines.push(`key.deserializer=${deserClass}`);
      lines.push(`value.deserializer=${deserClass}`);
      lines.push(`group.id=${groupId}`);
      lines.push(`auto.offset.reset=${autoOffsetReset}`);
      lines.push(`enable.auto.commit=${enableAutoCommit}`);
      lines.push(`max.poll.records=500`);
      lines.push(`session.timeout.ms=10000`);
      lines.push(`heartbeat.interval.ms=3000`);
      lines.push(`fetch.min.bytes=1`);
      lines.push(`fetch.max.wait.ms=500`);
    }

    if (securityProtocol === 'SASL_SSL') {
      lines.push('');
      lines.push('# SASL/SSL Configuration');
      lines.push('sasl.mechanism=PLAIN');
      lines.push('sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<USERNAME>" password="<PASSWORD>";');
      lines.push('ssl.endpoint.identification.algorithm=https');
    }

    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div>
            <label htmlFor={`${toolId}-type`} className="block text-sm font-medium text-gray-700 mb-1">Config Type</label>
            <select id={`${toolId}-type`} value={configType} onChange={(e) => setConfigType(e.target.value as 'producer' | 'consumer')} className="input-field" aria-label={`Config type for ${toolName}`}>
              <option value="producer">Producer</option>
              <option value="consumer">Consumer</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-bootstrap`} className="block text-sm font-medium text-gray-700 mb-1">Bootstrap Servers</label>
            <input id={`${toolId}-bootstrap`} type="text" value={bootstrapServers} onChange={(e) => setBootstrapServers(e.target.value)} className="input-field" aria-label="Bootstrap servers" />
          </div>
          {configType === 'consumer' && (
            <div>
              <label htmlFor={`${toolId}-group`} className="block text-sm font-medium text-gray-700 mb-1">Group ID</label>
              <input id={`${toolId}-group`} type="text" value={groupId} onChange={(e) => setGroupId(e.target.value)} className="input-field" aria-label="Consumer group ID" />
            </div>
          )}
          <div>
            <label htmlFor={`${toolId}-serializer`} className="block text-sm font-medium text-gray-700 mb-1">Serialization Format</label>
            <select id={`${toolId}-serializer`} value={serializer} onChange={(e) => setSerializer(e.target.value)} className="input-field" aria-label="Serialization format">
              <option value="string">String</option>
              <option value="json">JSON</option>
              <option value="avro">Avro</option>
            </select>
          </div>
          {configType === 'producer' && (
            <div>
              <label htmlFor={`${toolId}-acks`} className="block text-sm font-medium text-gray-700 mb-1">Acks</label>
              <select id={`${toolId}-acks`} value={acks} onChange={(e) => setAcks(e.target.value as 'all' | '1' | '0')} className="input-field" aria-label="Acknowledgment setting">
                <option value="all">all (strongest guarantee)</option>
                <option value="1">1 (leader only)</option>
                <option value="0">0 (fire and forget)</option>
              </select>
            </div>
          )}
          {configType === 'producer' && (
            <div className="grid grid-cols-2 gap-2">
              <div>
                <label htmlFor={`${toolId}-batch`} className="block text-sm font-medium text-gray-700 mb-1">Batch Size</label>
                <input id={`${toolId}-batch`} type="text" value={batchSize} onChange={(e) => setBatchSize(e.target.value)} className="input-field" aria-label="Batch size" />
              </div>
              <div>
                <label htmlFor={`${toolId}-linger`} className="block text-sm font-medium text-gray-700 mb-1">Linger (ms)</label>
                <input id={`${toolId}-linger`} type="text" value={lingerMs} onChange={(e) => setLingerMs(e.target.value)} className="input-field" aria-label="Linger milliseconds" />
              </div>
            </div>
          )}
          {configType === 'consumer' && (
            <div className="grid grid-cols-2 gap-2">
              <div>
                <label htmlFor={`${toolId}-offset`} className="block text-sm font-medium text-gray-700 mb-1">Auto Offset Reset</label>
                <select id={`${toolId}-offset`} value={autoOffsetReset} onChange={(e) => setAutoOffsetReset(e.target.value)} className="input-field" aria-label="Auto offset reset">
                  <option value="earliest">earliest</option>
                  <option value="latest">latest</option>
                  <option value="none">none</option>
                </select>
              </div>
              <div className="flex items-end">
                <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
                  <input type="checkbox" checked={enableAutoCommit} onChange={(e) => setEnableAutoCommit(e.target.checked)} aria-label="Enable auto commit" />
                  Auto Commit
                </label>
              </div>
            </div>
          )}
          <div>
            <label htmlFor={`${toolId}-security`} className="block text-sm font-medium text-gray-700 mb-1">Security Protocol</label>
            <select id={`${toolId}-security`} value={securityProtocol} onChange={(e) => setSecurityProtocol(e.target.value)} className="input-field" aria-label="Security protocol">
              <option value="PLAINTEXT">PLAINTEXT</option>
              <option value="SSL">SSL</option>
              <option value="SASL_PLAINTEXT">SASL_PLAINTEXT</option>
              <option value="SASL_SSL">SASL_SSL</option>
            </select>
          </div>
          <button onClick={generate} className="btn-primary w-full">Generate Kafka Config</button>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated Configuration</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-3 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
