'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * MemcachedConfigGenerator - Generate Memcached configuration files
 * with customizable memory, connections, threading, and network settings.
 */
export default function MemcachedConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [memory, setMemory] = useState('64');
  const [maxConnections, setMaxConnections] = useState('1024');
  const [threads, setThreads] = useState('4');
  const [port, setPort] = useState('11211');
  const [listenAddress, setListenAddress] = useState('127.0.0.1');
  const [maxItemSize, setMaxItemSize] = useState('1');
  const [evictionPolicy, setEvictionPolicy] = useState('lru');
  const [verbosity, setVerbosity] = useState('0');
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines: string[] = [
      '# Memcached Configuration',
      `# Generated by ${toolName}`,
      '',
      '# Memory allocation in megabytes',
      `-m ${memory}`,
      '',
      '# Listen address',
      `-l ${listenAddress}`,
      '',
      '# Port',
      `-p ${port}`,
      '',
      '# Max simultaneous connections',
      `-c ${maxConnections}`,
      '',
      '# Number of threads',
      `-t ${threads}`,
      '',
      '# Max item size in megabytes',
      `-I ${maxItemSize}m`,
      '',
      '# Verbosity level (0=none, 1=some, 2=lots)',
      `-v${verbosity !== '0' ? 'v'.repeat(parseInt(verbosity)) : ''}`,
      '',
      '# Run as daemon',
      '-d',
      '',
      `# Eviction policy: ${evictionPolicy}`,
      ...(evictionPolicy === 'lru' ? ['# Using default LRU eviction'] : ['-o modern', '# Using modern LRU with segmented approach']),
      '',
      '# --- Systemd service file example ---',
      '# [Unit]',
      '# Description=Memcached',
      '# After=network.target',
      '# ',
      '# [Service]',
      `# ExecStart=/usr/bin/memcached -m ${memory} -l ${listenAddress} -p ${port} -c ${maxConnections} -t ${threads} -I ${maxItemSize}m -u memcached`,
      '# Restart=always',
      '# ',
      '# [Install]',
      '# WantedBy=multi-user.target',
      '',
      '# --- Command line equivalent ---',
      `# memcached -m ${memory} -l ${listenAddress} -p ${port} -c ${maxConnections} -t ${threads} -I ${maxItemSize}m -d`,
    ];
    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-memory`} className="block text-sm font-medium text-gray-700 mb-1">Memory (MB)</label>
            <input id={`${toolId}-memory`} type="number" value={memory} onChange={(e) => setMemory(e.target.value)} className="input-field" aria-label={`Memory allocation for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-connections`} className="block text-sm font-medium text-gray-700 mb-1">Max Connections</label>
            <input id={`${toolId}-connections`} type="number" value={maxConnections} onChange={(e) => setMaxConnections(e.target.value)} className="input-field" aria-label="Max connections" />
          </div>
          <div>
            <label htmlFor={`${toolId}-threads`} className="block text-sm font-medium text-gray-700 mb-1">Threads</label>
            <input id={`${toolId}-threads`} type="number" value={threads} onChange={(e) => setThreads(e.target.value)} className="input-field" aria-label="Number of threads" />
          </div>
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port</label>
            <input id={`${toolId}-port`} type="number" value={port} onChange={(e) => setPort(e.target.value)} className="input-field" aria-label="Port number" />
          </div>
          <div>
            <label htmlFor={`${toolId}-listen`} className="block text-sm font-medium text-gray-700 mb-1">Listen Address</label>
            <input id={`${toolId}-listen`} type="text" value={listenAddress} onChange={(e) => setListenAddress(e.target.value)} className="input-field" aria-label="Listen address" />
          </div>
          <div>
            <label htmlFor={`${toolId}-itemsize`} className="block text-sm font-medium text-gray-700 mb-1">Max Item Size (MB)</label>
            <input id={`${toolId}-itemsize`} type="number" value={maxItemSize} onChange={(e) => setMaxItemSize(e.target.value)} className="input-field" aria-label="Max item size" />
          </div>
          <div>
            <label htmlFor={`${toolId}-eviction`} className="block text-sm font-medium text-gray-700 mb-1">Eviction Policy</label>
            <select id={`${toolId}-eviction`} value={evictionPolicy} onChange={(e) => setEvictionPolicy(e.target.value)} className="input-field" aria-label="Eviction policy">
              <option value="lru">LRU (Least Recently Used)</option>
              <option value="modern">Modern Segmented LRU</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-verbosity`} className="block text-sm font-medium text-gray-700 mb-1">Verbosity</label>
            <select id={`${toolId}-verbosity`} value={verbosity} onChange={(e) => setVerbosity(e.target.value)} className="input-field" aria-label="Verbosity level">
              <option value="0">None</option>
              <option value="1">Some</option>
              <option value="2">Lots</option>
            </select>
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Configuration</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Memcached Configuration</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-4 rounded-lg">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
