'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * RabbitmqConfigGenerator - Generate RabbitMQ configuration files
 * with customizable listeners, memory, disk, clustering, and plugin settings.
 */
export default function RabbitmqConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [port, setPort] = useState('5672');
  const [managementPort, setManagementPort] = useState('15672');
  const [memoryLimit, setMemoryLimit] = useState('0.4');
  const [diskFreeLimit, setDiskFreeLimit] = useState('50000000');
  const [defaultUser, setDefaultUser] = useState('guest');
  const [defaultVhost, setDefaultVhost] = useState('/');
  const [heartbeat, setHeartbeat] = useState('60');
  const [channelMax, setChannelMax] = useState('2047');
  const [enableManagement, setEnableManagement] = useState(true);
  const [enableShovel, setEnableShovel] = useState(false);
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines: string[] = [
      '## RabbitMQ Configuration',
      `## Generated by ${toolName}`,
      '',
      '## Networking',
      `listeners.tcp.default = ${port}`,
      ...(enableManagement ? [`management.tcp.port = ${managementPort}`] : []),
      '',
      '## Default user (change password in production!)',
      `default_user = ${defaultUser}`,
      `default_pass = changeme`,
      `default_vhost = ${defaultVhost}`,
      '',
      '## Memory and Disk',
      `vm_memory_high_watermark.relative = ${memoryLimit}`,
      `disk_free_limit.absolute = ${diskFreeLimit}`,
      '',
      '## Connection Settings',
      `heartbeat = ${heartbeat}`,
      `channel_max = ${channelMax}`,
      '',
      '## Logging',
      'log.file.level = info',
      'log.console = true',
      'log.console.level = info',
      '',
      '## Plugins',
      ...(enableManagement ? ['# Management plugin enabled via rabbitmq-plugins enable rabbitmq_management'] : []),
      ...(enableShovel ? ['# Shovel plugin enabled via rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management'] : []),
      '',
      '## Cluster Formation (uncomment for clustering)',
      '# cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config',
      '# cluster_formation.classic_config.nodes.1 = rabbit@node1',
      '# cluster_formation.classic_config.nodes.2 = rabbit@node2',
      '',
      '## TLS/SSL (uncomment and configure for production)',
      '# listeners.ssl.default = 5671',
      '# ssl_options.cacertfile = /path/to/ca_certificate.pem',
      '# ssl_options.certfile = /path/to/server_certificate.pem',
      '# ssl_options.keyfile = /path/to/server_key.pem',
      '# ssl_options.verify = verify_peer',
      '# ssl_options.fail_if_no_peer_cert = false',
    ];
    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">AMQP Port</label>
            <input id={`${toolId}-port`} type="number" value={port} onChange={(e) => setPort(e.target.value)} className="input-field" aria-label={`AMQP port for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-mgmt-port`} className="block text-sm font-medium text-gray-700 mb-1">Management Port</label>
            <input id={`${toolId}-mgmt-port`} type="number" value={managementPort} onChange={(e) => setManagementPort(e.target.value)} className="input-field" aria-label="Management port" />
          </div>
          <div>
            <label htmlFor={`${toolId}-memory`} className="block text-sm font-medium text-gray-700 mb-1">Memory Watermark (0-1)</label>
            <input id={`${toolId}-memory`} type="number" step="0.05" min="0.1" max="0.9" value={memoryLimit} onChange={(e) => setMemoryLimit(e.target.value)} className="input-field" aria-label="Memory high watermark" />
          </div>
          <div>
            <label htmlFor={`${toolId}-disk`} className="block text-sm font-medium text-gray-700 mb-1">Disk Free Limit (bytes)</label>
            <input id={`${toolId}-disk`} type="number" value={diskFreeLimit} onChange={(e) => setDiskFreeLimit(e.target.value)} className="input-field" aria-label="Disk free limit" />
          </div>
          <div>
            <label htmlFor={`${toolId}-user`} className="block text-sm font-medium text-gray-700 mb-1">Default User</label>
            <input id={`${toolId}-user`} type="text" value={defaultUser} onChange={(e) => setDefaultUser(e.target.value)} className="input-field" aria-label="Default user" />
          </div>
          <div>
            <label htmlFor={`${toolId}-vhost`} className="block text-sm font-medium text-gray-700 mb-1">Default VHost</label>
            <input id={`${toolId}-vhost`} type="text" value={defaultVhost} onChange={(e) => setDefaultVhost(e.target.value)} className="input-field" aria-label="Default vhost" />
          </div>
          <div>
            <label htmlFor={`${toolId}-heartbeat`} className="block text-sm font-medium text-gray-700 mb-1">Heartbeat (seconds)</label>
            <input id={`${toolId}-heartbeat`} type="number" value={heartbeat} onChange={(e) => setHeartbeat(e.target.value)} className="input-field" aria-label="Heartbeat interval" />
          </div>
          <div>
            <label htmlFor={`${toolId}-channels`} className="block text-sm font-medium text-gray-700 mb-1">Max Channels</label>
            <input id={`${toolId}-channels`} type="number" value={channelMax} onChange={(e) => setChannelMax(e.target.value)} className="input-field" aria-label="Max channels" />
          </div>
        </div>
        <div className="flex gap-4 mt-4">
          <label className="flex items-center gap-2 text-sm">
            <input type="checkbox" checked={enableManagement} onChange={(e) => setEnableManagement(e.target.checked)} aria-label="Enable management plugin" />
            Management Plugin
          </label>
          <label className="flex items-center gap-2 text-sm">
            <input type="checkbox" checked={enableShovel} onChange={(e) => setEnableShovel(e.target.checked)} aria-label="Enable shovel plugin" />
            Shovel Plugin
          </label>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Configuration</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">RabbitMQ Configuration (rabbitmq.conf)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-4 rounded-lg">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
