'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * RedisConfGenerator - Generate Redis redis.conf configuration files.
 * Produces configuration with memory, persistence, networking, and security settings.
 */
export default function RedisConfGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [port, setPort] = useState('6379');
  const [bind, setBind] = useState('127.0.0.1');
  const [maxMemory, setMaxMemory] = useState('256');
  const [maxMemoryPolicy, setMaxMemoryPolicy] = useState('allkeys-lru');
  const [persistence, setPersistence] = useState('rdb');
  const [password, setPassword] = useState('');
  const [databases, setDatabases] = useState('16');
  const [timeout, setTimeout] = useState('300');
  const [logLevel, setLogLevel] = useState('notice');
  const [output, setOutput] = useState('');

  const generate = () => {
    let conf = `# Redis Configuration\n# Generated by DeWelope Tools\n\n`;

    conf += `# NETWORK\nbind ${bind}\nport ${port}\ntcp-backlog 511\ntimeout ${timeout}\ntcp-keepalive 300\n\n`;

    conf += `# GENERAL\ndaemonize no\nsupervised no\npidfile /var/run/redis_${port}.pid\nloglevel ${logLevel}\nlogfile ""\ndatabases ${databases}\nalways-show-logo no\n\n`;

    if (password) {
      conf += `# SECURITY\nrequirepass ${password}\n\n`;
    }

    conf += `# MEMORY MANAGEMENT\nmaxmemory ${maxMemory}mb\nmaxmemory-policy ${maxMemoryPolicy}\nmaxmemory-samples 5\n\n`;

    if (persistence === 'rdb' || persistence === 'both') {
      conf += `# RDB PERSISTENCE\nsave 900 1\nsave 300 10\nsave 60 10000\nstop-writes-on-bgsave-error yes\nrdbcompression yes\nrdbchecksum yes\ndbfilename dump.rdb\ndir ./\n\n`;
    }

    if (persistence === 'aof' || persistence === 'both') {
      conf += `# AOF PERSISTENCE\nappendonly yes\nappendfilename "appendonly.aof"\nappendfsync everysec\nno-appendfsync-on-rewrite no\nauto-aof-rewrite-percentage 100\nauto-aof-rewrite-min-size 64mb\naof-load-truncated yes\naof-use-rdb-preamble yes\n\n`;
    }

    if (persistence === 'none') {
      conf += `# PERSISTENCE DISABLED\nsave ""\nappendonly no\n\n`;
    }

    conf += `# CLIENTS\nmaxclients 10000\n\n`;

    conf += `# LAZY FREEING\nlazyfree-lazy-eviction no\nlazyfree-lazy-expire no\nlazyfree-lazy-server-del no\nreplica-lazy-flush no\n\n`;

    conf += `# SLOW LOG\nslowlog-log-slower-than 10000\nslowlog-max-len 128\n`;

    setOutput(conf);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-bind`} className="block text-sm font-medium text-gray-700 mb-1">Bind Address</label>
            <input id={`${toolId}-bind`} type="text" value={bind} onChange={(e) => setBind(e.target.value)} className="input-field" aria-label={`Bind address for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port</label>
            <input id={`${toolId}-port`} type="text" value={port} onChange={(e) => setPort(e.target.value)} className="input-field" aria-label="Redis port" />
          </div>
          <div>
            <label htmlFor={`${toolId}-maxmem`} className="block text-sm font-medium text-gray-700 mb-1">Max Memory (MB)</label>
            <input id={`${toolId}-maxmem`} type="number" value={maxMemory} onChange={(e) => setMaxMemory(e.target.value)} className="input-field" aria-label="Max memory in MB" />
          </div>
          <div>
            <label htmlFor={`${toolId}-policy`} className="block text-sm font-medium text-gray-700 mb-1">Eviction Policy</label>
            <select id={`${toolId}-policy`} value={maxMemoryPolicy} onChange={(e) => setMaxMemoryPolicy(e.target.value)} className="input-field" aria-label="Eviction policy">
              <option value="noeviction">noeviction</option>
              <option value="allkeys-lru">allkeys-lru</option>
              <option value="allkeys-lfu">allkeys-lfu</option>
              <option value="volatile-lru">volatile-lru</option>
              <option value="volatile-lfu">volatile-lfu</option>
              <option value="allkeys-random">allkeys-random</option>
              <option value="volatile-random">volatile-random</option>
              <option value="volatile-ttl">volatile-ttl</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-persist`} className="block text-sm font-medium text-gray-700 mb-1">Persistence</label>
            <select id={`${toolId}-persist`} value={persistence} onChange={(e) => setPersistence(e.target.value)} className="input-field" aria-label="Persistence mode">
              <option value="rdb">RDB only</option>
              <option value="aof">AOF only</option>
              <option value="both">RDB + AOF</option>
              <option value="none">None (cache only)</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-loglevel`} className="block text-sm font-medium text-gray-700 mb-1">Log Level</label>
            <select id={`${toolId}-loglevel`} value={logLevel} onChange={(e) => setLogLevel(e.target.value)} className="input-field" aria-label="Log level">
              <option value="debug">debug</option>
              <option value="verbose">verbose</option>
              <option value="notice">notice</option>
              <option value="warning">warning</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-dbs`} className="block text-sm font-medium text-gray-700 mb-1">Databases</label>
            <input id={`${toolId}-dbs`} type="number" value={databases} onChange={(e) => setDatabases(e.target.value)} className="input-field" aria-label="Number of databases" />
          </div>
          <div>
            <label htmlFor={`${toolId}-timeout`} className="block text-sm font-medium text-gray-700 mb-1">Client Timeout (seconds)</label>
            <input id={`${toolId}-timeout`} type="number" value={timeout} onChange={(e) => setTimeout(e.target.value)} className="input-field" aria-label="Client timeout" />
          </div>
          <div className="md:col-span-2">
            <label htmlFor={`${toolId}-pass`} className="block text-sm font-medium text-gray-700 mb-1">Password (optional)</label>
            <input id={`${toolId}-pass`} type="text" value={password} onChange={(e) => setPassword(e.target.value)} className="input-field" placeholder="Leave empty for no auth" aria-label="Redis password" />
          </div>
        </div>
        <button onClick={generate} className="mt-4 btn-primary">Generate redis.conf</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated redis.conf</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto max-h-96">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
