'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * SaltStateGenerator - Generate SaltStack state file from definitions.
 * Converts user-defined state parameters into a SaltStack SLS (YAML) file.
 */
export default function SaltStateGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [states, setStates] = useState([
    { id: 'install_nginx', module: 'pkg', function: 'installed', name: 'nginx', properties: '' },
  ]);
  const [output, setOutput] = useState('');

  const addState = () => {
    setStates([...states, { id: '', module: 'pkg', function: 'installed', name: '', properties: '' }]);
  };

  const removeState = (index: number) => {
    setStates(states.filter((_, i) => i !== index));
  };

  const updateState = (index: number, field: string, value: string) => {
    const updated = [...states];
    updated[index] = { ...updated[index], [field]: value };
    setStates(updated);
  };

  const generate = () => {
    const lines: string[] = [];
    lines.push('# SaltStack State File');
    lines.push('# Generated by DeWelope Tools');
    lines.push('');

    states.forEach((state) => {
      if (!state.id) return;
      lines.push(`${state.id}:`);
      lines.push(`  ${state.module}.${state.function}:`);
      if (state.name) {
        lines.push(`    - name: ${state.name}`);
      }
      if (state.properties.trim()) {
        state.properties.split('\n').forEach((prop) => {
          const trimmed = prop.trim();
          if (trimmed) lines.push(`    - ${trimmed}`);
        });
      }
      lines.push('');
    });

    setOutput(lines.join('\n'));
  };

  const modules = ['pkg', 'service', 'file', 'cmd', 'user', 'group', 'cron', 'git', 'pip', 'npm'];
  const functions: Record<string, string[]> = {
    pkg: ['installed', 'removed', 'latest', 'purged'],
    service: ['running', 'dead', 'enabled', 'disabled'],
    file: ['managed', 'directory', 'absent', 'symlink', 'recurse'],
    cmd: ['run', 'wait', 'script'],
    user: ['present', 'absent'],
    group: ['present', 'absent'],
    cron: ['present', 'absent'],
    git: ['latest', 'present'],
    pip: ['installed', 'removed'],
    npm: ['installed', 'removed'],
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <label className="block text-sm font-medium text-gray-700">State Definitions</label>
          {states.map((state, idx) => (
            <div key={idx} className="border border-gray-200 rounded-lg p-3 space-y-2">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <input
                  type="text"
                  value={state.id}
                  onChange={(e) => updateState(idx, 'id', e.target.value)}
                  placeholder="State ID (e.g. install_nginx)"
                  className="input-field"
                  aria-label={`State ID for ${toolName}`}
                />
                <input
                  type="text"
                  value={state.name}
                  onChange={(e) => updateState(idx, 'name', e.target.value)}
                  placeholder="Name (e.g. nginx)"
                  className="input-field"
                  aria-label="State name"
                />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <select
                  value={state.module}
                  onChange={(e) => updateState(idx, 'module', e.target.value)}
                  className="input-field"
                  aria-label="Salt module"
                >
                  {modules.map((m) => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </select>
                <select
                  value={state.function}
                  onChange={(e) => updateState(idx, 'function', e.target.value)}
                  className="input-field"
                  aria-label="Salt function"
                >
                  {(functions[state.module] || ['present', 'absent']).map((f) => (
                    <option key={f} value={f}>{f}</option>
                  ))}
                </select>
              </div>
              <textarea
                value={state.properties}
                onChange={(e) => updateState(idx, 'properties', e.target.value)}
                placeholder="Additional properties (one per line, e.g. require: pkg: nginx)"
                className="input-field h-16 resize-y font-mono text-sm"
                aria-label="State properties"
              />
              <button
                onClick={() => removeState(idx)}
                className="text-sm text-red-600 hover:text-red-800"
              >
                Remove
              </button>
            </div>
          ))}
          <button
            onClick={addState}
            className="text-sm text-blue-600 hover:text-blue-800 font-medium"
          >
            + Add State
          </button>
        </div>

        <button
          onClick={generate}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          Generate State File
        </button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated SaltStack State (SLS)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
