'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * SconsBuildGenerator - Generate SCons build script from project config.
 */
export default function SconsBuildGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [projectName, setProjectName] = useState('');
  const [language, setLanguage] = useState('c');
  const [sources, setSources] = useState('');
  const [targetType, setTargetType] = useState('Program');
  const [cflags, setCflags] = useState('-Wall -O2');
  const [libs, setLibs] = useState('');
  const [libPaths, setLibPaths] = useState('');
  const [output, setOutput] = useState('');

  const generate = () => {
    if (!projectName.trim()) {
      setOutput('Error: Project name is required.');
      return;
    }

    const lines: string[] = [];
    lines.push('# SConstruct - Generated by DeWelope Tools');
    lines.push('');
    lines.push("env = Environment()");
    lines.push('');

    if (cflags.trim()) {
      if (language === 'cpp') {
        lines.push(`env.Append(CXXFLAGS='${cflags.trim()}')`);
      } else {
        lines.push(`env.Append(CCFLAGS='${cflags.trim()}')`);
      }
    }

    const libList = libs.trim().split(/[,\n]+/).map(l => l.trim()).filter(Boolean);
    if (libList.length > 0) {
      lines.push(`env.Append(LIBS=[${libList.map(l => `'${l}'`).join(', ')}])`);
    }

    const libPathList = libPaths.trim().split(/[,\n]+/).map(l => l.trim()).filter(Boolean);
    if (libPathList.length > 0) {
      lines.push(`env.Append(LIBPATH=[${libPathList.map(l => `'${l}'`).join(', ')}])`);
    }

    lines.push('');

    const srcList = sources.trim().split(/[,\n]+/).map(s => s.trim()).filter(Boolean);
    const srcStr = srcList.length > 0
      ? `[${srcList.map(s => `'${s}'`).join(', ')}]`
      : `['src/main.${language === 'cpp' ? 'cpp' : 'c'}']`;

    lines.push(`env.${targetType}('${projectName.trim()}', ${srcStr})`);

    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-name`} className="block text-sm font-medium text-gray-700 mb-1">Project/Target Name</label>
            <input id={`${toolId}-name`} type="text" value={projectName} onChange={(e) => setProjectName(e.target.value)} placeholder="my_app" aria-label={`Project name for ${toolName}`} className="input-field" />
          </div>
          <div>
            <label htmlFor={`${toolId}-lang`} className="block text-sm font-medium text-gray-700 mb-1">Language</label>
            <select id={`${toolId}-lang`} value={language} onChange={(e) => setLanguage(e.target.value)} className="input-field" aria-label="Programming language">
              <option value="c">C</option>
              <option value="cpp">C++</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-target`} className="block text-sm font-medium text-gray-700 mb-1">Target Type</label>
            <select id={`${toolId}-target`} value={targetType} onChange={(e) => setTargetType(e.target.value)} className="input-field" aria-label="Target type">
              <option value="Program">Program (Executable)</option>
              <option value="SharedLibrary">Shared Library</option>
              <option value="StaticLibrary">Static Library</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-cflags`} className="block text-sm font-medium text-gray-700 mb-1">Compiler Flags</label>
            <input id={`${toolId}-cflags`} type="text" value={cflags} onChange={(e) => setCflags(e.target.value)} placeholder="-Wall -O2" className="input-field" aria-label="Compiler flags" />
          </div>
        </div>
        <div className="mt-4">
          <label htmlFor={`${toolId}-sources`} className="block text-sm font-medium text-gray-700 mb-1">Source Files (comma or newline separated)</label>
          <textarea id={`${toolId}-sources`} value={sources} onChange={(e) => setSources(e.target.value)} placeholder="src/main.c, src/utils.c" className="input-field h-20 resize-y font-mono" aria-label="Source files" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
          <div>
            <label htmlFor={`${toolId}-libs`} className="block text-sm font-medium text-gray-700 mb-1">Libraries (comma separated)</label>
            <input id={`${toolId}-libs`} type="text" value={libs} onChange={(e) => setLibs(e.target.value)} placeholder="m, pthread" className="input-field" aria-label="Libraries" />
          </div>
          <div>
            <label htmlFor={`${toolId}-libpaths`} className="block text-sm font-medium text-gray-700 mb-1">Library Paths (comma separated)</label>
            <input id={`${toolId}-libpaths`} type="text" value={libPaths} onChange={(e) => setLibPaths(e.target.value)} placeholder="/usr/local/lib" className="input-field" aria-label="Library paths" />
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate SConstruct</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">SConstruct</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-4 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
