'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

interface Variable {
  name: string;
  type: 'numeric' | 'string';
  label: string;
  width: number;
  decimals: number;
  values: string;
  missing: string;
}

/**
 * SpssSyntaxGenerator - Generate SPSS syntax from variable definitions.
 * Allows users to define variables and produces VARIABLE LABELS, VALUE LABELS,
 * and MISSING VALUES syntax blocks.
 */
export default function SpssSyntaxGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [variables, setVariables] = useState<Variable[]>([
    { name: '', type: 'numeric', label: '', width: 8, decimals: 2, values: '', missing: '' }
  ]);
  const [output, setOutput] = useState('');

  const addVariable = () => {
    setVariables([...variables, { name: '', type: 'numeric', label: '', width: 8, decimals: 2, values: '', missing: '' }]);
  };

  const removeVariable = (index: number) => {
    if (variables.length > 1) {
      setVariables(variables.filter((_, i) => i !== index));
    }
  };

  const updateVariable = (index: number, field: keyof Variable, value: string | number) => {
    const updated = [...variables];
    updated[index] = { ...updated[index], [field]: value };
    setVariables(updated);
  };

  const generate = () => {
    const validVars = variables.filter(v => v.name.trim());
    if (validVars.length === 0) {
      setOutput('* Error: At least one variable with a name is required.');
      return;
    }

    const lines: string[] = [];
    lines.push('* SPSS Syntax generated by DeWelope Tools.');
    lines.push('');

    // DATA LIST
    lines.push('DATA LIST FREE');
    lines.push('  / ' + validVars.map(v => {
      if (v.type === 'string') {
        return `${v.name} (A${v.width})`;
      }
      return `${v.name} (F${v.width}.${v.decimals})`;
    }).join(' '));
    lines.push('.');
    lines.push('');

    // VARIABLE LABELS
    const labeled = validVars.filter(v => v.label.trim());
    if (labeled.length > 0) {
      lines.push('VARIABLE LABELS');
      labeled.forEach((v, i) => {
        const end = i === labeled.length - 1 ? '.' : '';
        lines.push(`  ${v.name} "${v.label}"${end}`);
      });
      lines.push('');
    }

    // VALUE LABELS
    const valued = validVars.filter(v => v.values.trim());
    valued.forEach(v => {
      lines.push(`VALUE LABELS ${v.name}`);
      const pairs = v.values.split(',').map(p => p.trim());
      pairs.forEach((pair, i) => {
        const [code, label] = pair.split('=').map(s => s.trim());
        if (code && label) {
          const end = i === pairs.length - 1 ? '.' : '';
          lines.push(`  ${code} "${label}"${end}`);
        }
      });
      lines.push('');
    });

    // MISSING VALUES
    const missings = validVars.filter(v => v.missing.trim());
    if (missings.length > 0) {
      missings.forEach(v => {
        lines.push(`MISSING VALUES ${v.name} (${v.missing}).`);
      });
      lines.push('');
    }

    lines.push('EXECUTE.');
    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Define Variables
        </label>
        {variables.map((v, i) => (
          <div key={i} className="border border-gray-200 rounded p-3 mb-3 space-y-2">
            <div className="flex gap-2 flex-wrap">
              <input
                type="text"
                value={v.name}
                onChange={(e) => updateVariable(i, 'name', e.target.value)}
                placeholder="Variable name"
                aria-label={`Variable ${i + 1} name for ${toolName}`}
                className="input-field flex-1 min-w-[120px]"
              />
              <select
                value={v.type}
                onChange={(e) => updateVariable(i, 'type', e.target.value)}
                aria-label={`Variable ${i + 1} type`}
                className="input-field w-28"
              >
                <option value="numeric">Numeric</option>
                <option value="string">String</option>
              </select>
              <input
                type="number"
                value={v.width}
                onChange={(e) => updateVariable(i, 'width', parseInt(e.target.value) || 8)}
                placeholder="Width"
                aria-label={`Variable ${i + 1} width`}
                className="input-field w-20"
              />
              <input
                type="number"
                value={v.decimals}
                onChange={(e) => updateVariable(i, 'decimals', parseInt(e.target.value) || 0)}
                placeholder="Dec"
                aria-label={`Variable ${i + 1} decimals`}
                className="input-field w-20"
              />
            </div>
            <input
              type="text"
              value={v.label}
              onChange={(e) => updateVariable(i, 'label', e.target.value)}
              placeholder="Variable label (e.g., Age of respondent)"
              aria-label={`Variable ${i + 1} label`}
              className="input-field w-full"
            />
            <input
              type="text"
              value={v.values}
              onChange={(e) => updateVariable(i, 'values', e.target.value)}
              placeholder="Value labels: 1=Male, 2=Female"
              aria-label={`Variable ${i + 1} value labels`}
              className="input-field w-full"
            />
            <div className="flex gap-2">
              <input
                type="text"
                value={v.missing}
                onChange={(e) => updateVariable(i, 'missing', e.target.value)}
                placeholder="Missing values (e.g., 99, -1)"
                aria-label={`Variable ${i + 1} missing values`}
                className="input-field flex-1"
              />
              <button
                onClick={() => removeVariable(i)}
                className="px-3 py-1 text-sm text-red-600 hover:bg-red-50 rounded"
                aria-label={`Remove variable ${i + 1}`}
              >
                Remove
              </button>
            </div>
          </div>
        ))}
        <div className="flex gap-2">
          <button onClick={addVariable} className="btn-secondary text-sm">
            + Add Variable
          </button>
          <button onClick={generate} className="btn-primary text-sm">
            Generate SPSS Syntax
          </button>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated SPSS Syntax</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-3 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
