'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * SquidProxyConfigGenerator - Generate Squid proxy configuration.
 * Creates squid.conf files with common proxy settings.
 */
export default function SquidProxyConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [port, setPort] = useState('3128');
  const [hostname, setHostname] = useState('proxy.example.com');
  const [cacheSize, setCacheSize] = useState('256');
  const [maxObjectSize, setMaxObjectSize] = useState('64');
  const [allowedNetworks, setAllowedNetworks] = useState('192.168.1.0/24\n10.0.0.0/8');
  const [blockedDomains, setBlockedDomains] = useState('');
  const [enableLogging, setEnableLogging] = useState(true);
  const [enableSsl, setEnableSsl] = useState(false);
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines: string[] = [];
    lines.push('# Squid proxy configuration');
    lines.push('# Generated by DeWelope Tools');
    lines.push('');
    lines.push(`http_port ${port}`);
    lines.push(`visible_hostname ${hostname}`);
    lines.push('');
    lines.push('# Cache settings');
    lines.push(`cache_mem ${cacheSize} MB`);
    lines.push(`maximum_object_size ${maxObjectSize} MB`);
    lines.push('cache_dir ufs /var/spool/squid 100 16 256');
    lines.push('');
    lines.push('# ACL definitions');
    lines.push('acl SSL_ports port 443');
    lines.push('acl Safe_ports port 80');
    lines.push('acl Safe_ports port 443');
    lines.push('acl Safe_ports port 21');
    lines.push('acl CONNECT method CONNECT');
    lines.push('');

    const networks = allowedNetworks.split('\n').filter(n => n.trim());
    if (networks.length > 0) {
      networks.forEach((net, i) => {
        lines.push(`acl localnet${i} src ${net.trim()}`);
      });
      lines.push('');
      networks.forEach((_, i) => {
        lines.push(`http_access allow localnet${i}`);
      });
    }
    lines.push('');

    if (blockedDomains.trim()) {
      lines.push('# Blocked domains');
      lines.push('acl blocked_sites dstdomain ' + blockedDomains.split('\n').filter(d => d.trim()).map(d => d.trim()).join(' '));
      lines.push('http_access deny blocked_sites');
      lines.push('');
    }

    lines.push('# Security');
    lines.push('http_access deny !Safe_ports');
    lines.push('http_access deny CONNECT !SSL_ports');
    lines.push('http_access allow localhost');
    lines.push('http_access deny all');
    lines.push('');

    if (enableSsl) {
      lines.push('# SSL/TLS');
      lines.push(`https_port ${parseInt(port) + 1} intercept ssl-bump cert=/etc/squid/ssl_cert/myCA.pem key=/etc/squid/ssl_cert/myCA.key`);
      lines.push('ssl_bump peek all');
      lines.push('ssl_bump splice all');
      lines.push('');
    }

    if (enableLogging) {
      lines.push('# Logging');
      lines.push('access_log /var/log/squid/access.log squid');
      lines.push('cache_log /var/log/squid/cache.log');
      lines.push('cache_store_log /var/log/squid/store.log');
    } else {
      lines.push('# Logging disabled');
      lines.push('access_log none');
      lines.push('cache_log /dev/null');
    }

    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Listen Port</label>
            <input id={`${toolId}-port`} type="text" value={port} onChange={(e) => setPort(e.target.value)} className="input-field" aria-label={`Listen port for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-hostname`} className="block text-sm font-medium text-gray-700 mb-1">Visible Hostname</label>
            <input id={`${toolId}-hostname`} type="text" value={hostname} onChange={(e) => setHostname(e.target.value)} className="input-field" aria-label="Visible hostname" />
          </div>
          <div>
            <label htmlFor={`${toolId}-cache`} className="block text-sm font-medium text-gray-700 mb-1">Cache Memory (MB)</label>
            <input id={`${toolId}-cache`} type="number" value={cacheSize} onChange={(e) => setCacheSize(e.target.value)} className="input-field" aria-label="Cache memory in MB" />
          </div>
          <div>
            <label htmlFor={`${toolId}-maxobj`} className="block text-sm font-medium text-gray-700 mb-1">Max Object Size (MB)</label>
            <input id={`${toolId}-maxobj`} type="number" value={maxObjectSize} onChange={(e) => setMaxObjectSize(e.target.value)} className="input-field" aria-label="Max object size in MB" />
          </div>
          <div className="md:col-span-2">
            <label htmlFor={`${toolId}-networks`} className="block text-sm font-medium text-gray-700 mb-1">Allowed Networks (one per line)</label>
            <textarea id={`${toolId}-networks`} value={allowedNetworks} onChange={(e) => setAllowedNetworks(e.target.value)} className="input-field h-24 resize-y font-mono" aria-label="Allowed networks" />
          </div>
          <div className="md:col-span-2">
            <label htmlFor={`${toolId}-blocked`} className="block text-sm font-medium text-gray-700 mb-1">Blocked Domains (one per line, optional)</label>
            <textarea id={`${toolId}-blocked`} value={blockedDomains} onChange={(e) => setBlockedDomains(e.target.value)} placeholder=".example.com&#10;.ads.net" className="input-field h-20 resize-y font-mono" aria-label="Blocked domains" />
          </div>
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={enableLogging} onChange={(e) => setEnableLogging(e.target.checked)} className="rounded" />
              Enable Logging
            </label>
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={enableSsl} onChange={(e) => setEnableSsl(e.target.checked)} className="rounded" />
              Enable SSL Bump
            </label>
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Config</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Squid Configuration</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
