'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

export default function StackYamlGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [resolver, setResolver] = useState('lts-21.25');
  const [packages, setPackages] = useState('.');
  const [extraDeps, setExtraDeps] = useState('');
  const [ghcOptions, setGhcOptions] = useState('-Wall');
  const [output, setOutput] = useState('');

  const generate = () => {
    const pkgList = packages.split(',').map(p => p.trim()).filter(Boolean);
    const extraDepList = extraDeps.split(',').map(d => d.trim()).filter(Boolean);

    let result = `# stack.yaml - Generated by DeWelope Tools
resolver: ${resolver}

packages:
${pkgList.map(p => `  - ${p}`).join('\n')}
`;

    if (extraDepList.length > 0) {
      result += `\nextra-deps:
${extraDepList.map(d => `  - ${d}`).join('\n')}
`;
    }

    if (ghcOptions) {
      result += `\nghc-options:
  "$locals": ${ghcOptions}
`;
    }

    result += `\n# Uncomment to use system GHC
# system-ghc: true
# install-ghc: false

# Uncomment for Nix integration
# nix:
#   enable: true
#   packages: [zlib]
`;

    setOutput(result);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div>
            <label htmlFor={`${toolId}-resolver`} className="block text-sm font-medium text-gray-700 mb-1">Resolver (LTS or Nightly)</label>
            <input id={`${toolId}-resolver`} type="text" value={resolver} onChange={(e) => setResolver(e.target.value)} className="input-field" placeholder="lts-21.25" aria-label={`Resolver for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-packages`} className="block text-sm font-medium text-gray-700 mb-1">Packages (comma-separated paths)</label>
            <input id={`${toolId}-packages`} type="text" value={packages} onChange={(e) => setPackages(e.target.value)} className="input-field" placeholder="., ./subpackage" aria-label="Packages" />
          </div>
          <div>
            <label htmlFor={`${toolId}-extra`} className="block text-sm font-medium text-gray-700 mb-1">Extra Dependencies (comma-separated)</label>
            <input id={`${toolId}-extra`} type="text" value={extraDeps} onChange={(e) => setExtraDeps(e.target.value)} className="input-field" placeholder="acme-missiles-0.3" aria-label="Extra dependencies" />
          </div>
          <div>
            <label htmlFor={`${toolId}-ghc`} className="block text-sm font-medium text-gray-700 mb-1">GHC Options</label>
            <input id={`${toolId}-ghc`} type="text" value={ghcOptions} onChange={(e) => setGhcOptions(e.target.value)} className="input-field" placeholder="-Wall -Werror" aria-label="GHC options" />
          </div>
          <button onClick={generate} className="btn-primary">Generate stack.yaml</button>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated stack.yaml</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
