'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * StunnelConfigGenerator - Generate stunnel TLS wrapper configuration.
 * Creates stunnel config files for wrapping plain TCP connections with TLS/SSL.
 */
export default function StunnelConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [serviceName, setServiceName] = useState('myservice');
  const [mode, setMode] = useState<'client' | 'server'>('client');
  const [acceptHost, setAcceptHost] = useState('127.0.0.1');
  const [acceptPort, setAcceptPort] = useState('8443');
  const [connectHost, setConnectHost] = useState('remote.example.com');
  const [connectPort, setConnectPort] = useState('443');
  const [certFile, setCertFile] = useState('/etc/stunnel/stunnel.pem');
  const [keyFile, setKeyFile] = useState('/etc/stunnel/stunnel.key');
  const [caFile, setCaFile] = useState('/etc/stunnel/ca-certs.pem');
  const [verifyLevel, setVerifyLevel] = useState('2');
  const [output, setOutput] = useState('');

  const generate = () => {
    const lines: string[] = [];
    lines.push('; stunnel configuration file');
    lines.push('; Generated by DeWelope Tools');
    lines.push('');
    lines.push('[' + serviceName + ']');
    lines.push(`client = ${mode === 'client' ? 'yes' : 'no'}`);
    lines.push(`accept = ${acceptHost}:${acceptPort}`);
    lines.push(`connect = ${connectHost}:${connectPort}`);
    lines.push('');
    if (mode === 'server' || certFile) {
      lines.push(`cert = ${certFile}`);
    }
    if (mode === 'server' || keyFile) {
      lines.push(`key = ${keyFile}`);
    }
    if (caFile) {
      lines.push(`CAfile = ${caFile}`);
    }
    if (verifyLevel !== '0') {
      lines.push(`verify = ${verifyLevel}`);
    }
    lines.push('');
    lines.push('; TLS options');
    lines.push('options = NO_SSLv2');
    lines.push('options = NO_SSLv3');
    lines.push('TIMEOUTclose = 0');

    setOutput(lines.join('\n'));
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-service`} className="block text-sm font-medium text-gray-700 mb-1">Service Name</label>
            <input id={`${toolId}-service`} type="text" value={serviceName} onChange={(e) => setServiceName(e.target.value)} className="input-field" aria-label={`Service name for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-mode`} className="block text-sm font-medium text-gray-700 mb-1">Mode</label>
            <select id={`${toolId}-mode`} value={mode} onChange={(e) => setMode(e.target.value as 'client' | 'server')} className="input-field" aria-label="Stunnel mode">
              <option value="client">Client</option>
              <option value="server">Server</option>
            </select>
          </div>
          <div>
            <label htmlFor={`${toolId}-accept-host`} className="block text-sm font-medium text-gray-700 mb-1">Accept Host</label>
            <input id={`${toolId}-accept-host`} type="text" value={acceptHost} onChange={(e) => setAcceptHost(e.target.value)} className="input-field" aria-label="Accept host" />
          </div>
          <div>
            <label htmlFor={`${toolId}-accept-port`} className="block text-sm font-medium text-gray-700 mb-1">Accept Port</label>
            <input id={`${toolId}-accept-port`} type="text" value={acceptPort} onChange={(e) => setAcceptPort(e.target.value)} className="input-field" aria-label="Accept port" />
          </div>
          <div>
            <label htmlFor={`${toolId}-connect-host`} className="block text-sm font-medium text-gray-700 mb-1">Connect Host</label>
            <input id={`${toolId}-connect-host`} type="text" value={connectHost} onChange={(e) => setConnectHost(e.target.value)} className="input-field" aria-label="Connect host" />
          </div>
          <div>
            <label htmlFor={`${toolId}-connect-port`} className="block text-sm font-medium text-gray-700 mb-1">Connect Port</label>
            <input id={`${toolId}-connect-port`} type="text" value={connectPort} onChange={(e) => setConnectPort(e.target.value)} className="input-field" aria-label="Connect port" />
          </div>
          <div>
            <label htmlFor={`${toolId}-cert`} className="block text-sm font-medium text-gray-700 mb-1">Certificate File</label>
            <input id={`${toolId}-cert`} type="text" value={certFile} onChange={(e) => setCertFile(e.target.value)} className="input-field" aria-label="Certificate file path" />
          </div>
          <div>
            <label htmlFor={`${toolId}-key`} className="block text-sm font-medium text-gray-700 mb-1">Key File</label>
            <input id={`${toolId}-key`} type="text" value={keyFile} onChange={(e) => setKeyFile(e.target.value)} className="input-field" aria-label="Key file path" />
          </div>
          <div>
            <label htmlFor={`${toolId}-ca`} className="block text-sm font-medium text-gray-700 mb-1">CA File</label>
            <input id={`${toolId}-ca`} type="text" value={caFile} onChange={(e) => setCaFile(e.target.value)} className="input-field" aria-label="CA file path" />
          </div>
          <div>
            <label htmlFor={`${toolId}-verify`} className="block text-sm font-medium text-gray-700 mb-1">Verify Level</label>
            <select id={`${toolId}-verify`} value={verifyLevel} onChange={(e) => setVerifyLevel(e.target.value)} className="input-field" aria-label="Verify level">
              <option value="0">0 - No verification</option>
              <option value="1">1 - Verify if present</option>
              <option value="2">2 - Require valid cert</option>
              <option value="3">3 - Verify against local CRL</option>
            </select>
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Config</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">stunnel Configuration</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
