'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * UfwRuleGenerator - Generate UFW (Uncomplicated Firewall) rules for Ubuntu/Debian.
 * Supports allow/deny rules, port ranges, protocols, and application profiles.
 */
export default function UfwRuleGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [action, setAction] = useState('allow');
  const [direction, setDirection] = useState('in');
  const [protocol, setProtocol] = useState('tcp');
  const [port, setPort] = useState('');
  const [fromIp, setFromIp] = useState('');
  const [toIp, setToIp] = useState('');
  const [comment, setComment] = useState('');
  const [rules, setRules] = useState<string[]>([]);
  const [output, setOutput] = useState('');

  const addRule = () => {
    const parts: string[] = ['sudo ufw'];

    if (direction !== 'in') {
      parts.push(`route ${action}`);
    } else {
      parts.push(action);
    }

    if (direction !== 'in') {
      parts.push(`${direction}`);
    }

    if (fromIp.trim()) parts.push(`from ${fromIp.trim()}`);
    if (toIp.trim()) parts.push(`to ${toIp.trim()}`);
    if (port.trim()) {
      if (protocol === 'any') {
        parts.push(`port ${port.trim()}`);
      } else {
        parts.push(`proto ${protocol} port ${port.trim()}`);
      }
    } else if (protocol !== 'any' && !fromIp && !toIp) {
      parts.push(`proto ${protocol}`);
    }
    if (comment.trim()) parts.push(`comment '${comment.trim()}'`);

    const rule = parts.join(' ');
    const newRules = [...rules, rule];
    setRules(newRules);
    generateOutput(newRules);
  };

  const addPreset = (preset: string) => {
    let newRules: string[] = [];
    switch (preset) {
      case 'ssh':
        newRules = [...rules, 'sudo ufw allow 22/tcp comment \'SSH\''];
        break;
      case 'web':
        newRules = [...rules, 'sudo ufw allow 80/tcp comment \'HTTP\'', 'sudo ufw allow 443/tcp comment \'HTTPS\''];
        break;
      case 'mysql':
        newRules = [...rules, 'sudo ufw allow from 10.0.0.0/8 to any port 3306 proto tcp comment \'MySQL\''];
        break;
      case 'deny-all':
        newRules = [...rules, 'sudo ufw default deny incoming', 'sudo ufw default allow outgoing'];
        break;
      default:
        return;
    }
    setRules(newRules);
    generateOutput(newRules);
  };

  const generateOutput = (ruleList: string[]) => {
    let result = '#!/bin/bash\n';
    result += '# UFW Firewall Rules\n';
    result += '# Generated by DeWelope Tools\n\n';
    result += '# Reset UFW to defaults\n';
    result += 'sudo ufw --force reset\n\n';
    result += '# Set default policies\n';
    result += 'sudo ufw default deny incoming\n';
    result += 'sudo ufw default allow outgoing\n\n';
    result += '# Allow loopback\n';
    result += 'sudo ufw allow in on lo\n\n';
    result += '# Custom rules\n';
    ruleList.forEach(rule => {
      result += `${rule}\n`;
    });
    result += '\n# Enable UFW\n';
    result += 'sudo ufw --force enable\n\n';
    result += '# Check status\n';
    result += 'sudo ufw status verbose\n';

    setOutput(result);
  };

  const clearRules = () => {
    setRules([]);
    setOutput('');
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="flex gap-2 flex-wrap">
            <button onClick={() => addPreset('ssh')} className="btn-secondary text-xs">+ SSH (22)</button>
            <button onClick={() => addPreset('web')} className="btn-secondary text-xs">+ HTTP/HTTPS</button>
            <button onClick={() => addPreset('mysql')} className="btn-secondary text-xs">+ MySQL (LAN)</button>
            <button onClick={() => addPreset('deny-all')} className="btn-secondary text-xs">+ Default Deny</button>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label htmlFor={`${toolId}-action`} className="block text-sm font-medium text-gray-700 mb-1">Action</label>
              <select id={`${toolId}-action`} value={action} onChange={(e) => setAction(e.target.value)} className="input-field" aria-label={`Action for ${toolName}`}>
                <option value="allow">Allow</option>
                <option value="deny">Deny</option>
                <option value="reject">Reject</option>
                <option value="limit">Limit</option>
              </select>
            </div>
            <div>
              <label htmlFor={`${toolId}-direction`} className="block text-sm font-medium text-gray-700 mb-1">Direction</label>
              <select id={`${toolId}-direction`} value={direction} onChange={(e) => setDirection(e.target.value)} className="input-field">
                <option value="in">In</option>
                <option value="out">Out</option>
              </select>
            </div>
            <div>
              <label htmlFor={`${toolId}-protocol`} className="block text-sm font-medium text-gray-700 mb-1">Protocol</label>
              <select id={`${toolId}-protocol`} value={protocol} onChange={(e) => setProtocol(e.target.value)} className="input-field">
                <option value="tcp">TCP</option>
                <option value="udp">UDP</option>
                <option value="any">Any</option>
              </select>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Port(s)</label>
              <input id={`${toolId}-port`} type="text" value={port} onChange={(e) => setPort(e.target.value)} placeholder="80, 443, 8000:9000" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-from`} className="block text-sm font-medium text-gray-700 mb-1">From IP/Subnet</label>
              <input id={`${toolId}-from`} type="text" value={fromIp} onChange={(e) => setFromIp(e.target.value)} placeholder="192.168.1.0/24" className="input-field" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor={`${toolId}-to`} className="block text-sm font-medium text-gray-700 mb-1">To IP/Subnet</label>
              <input id={`${toolId}-to`} type="text" value={toIp} onChange={(e) => setToIp(e.target.value)} placeholder="10.0.0.1" className="input-field" />
            </div>
            <div>
              <label htmlFor={`${toolId}-comment`} className="block text-sm font-medium text-gray-700 mb-1">Comment</label>
              <input id={`${toolId}-comment`} type="text" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Allow web traffic" className="input-field" />
            </div>
          </div>
          <div className="flex gap-2">
            <button onClick={addRule} className="btn-primary">Add Rule</button>
            <button onClick={clearRules} className="btn-secondary">Clear All</button>
          </div>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated UFW Script ({rules.length} custom rules)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-3 rounded">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
