'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * VaultPolicyGenerator - Generate HashiCorp Vault policy HCL.
 * Create Vault policies with path-based access control rules.
 */
export default function VaultPolicyGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [policyName, setPolicyName] = useState('my-app-policy');
  const [rules, setRules] = useState([
    { path: 'secret/data/my-app/*', capabilities: ['read', 'list'] },
  ]);
  const [output, setOutput] = useState('');

  const allCapabilities = ['create', 'read', 'update', 'delete', 'list', 'sudo', 'deny'];

  const addRule = () => {
    setRules([...rules, { path: '', capabilities: ['read'] }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updatePath = (index: number, path: string) => {
    const updated = [...rules];
    updated[index] = { ...updated[index], path };
    setRules(updated);
  };

  const toggleCapability = (index: number, cap: string) => {
    const updated = [...rules];
    const current = updated[index].capabilities;
    if (current.includes(cap)) {
      updated[index] = { ...updated[index], capabilities: current.filter(c => c !== cap) };
    } else {
      updated[index] = { ...updated[index], capabilities: [...current, cap] };
    }
    setRules(updated);
  };

  const generate = () => {
    const lines: string[] = [];
    lines.push(`# Vault Policy: ${policyName}`);
    lines.push(`# Generated by DeWelope Tools`);
    lines.push('');

    for (const rule of rules) {
      if (!rule.path) continue;
      lines.push(`path "${rule.path}" {`);
      lines.push(`  capabilities = [${rule.capabilities.map(c => `"${c}"`).join(', ')}]`);
      lines.push('}');
      lines.push('');
    }

    setOutput(lines.join('\n').trim());
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-4">
          <div>
            <label htmlFor={`${toolId}-policy-name`} className="block text-sm font-medium text-gray-700 mb-1">Policy Name</label>
            <input id={`${toolId}-policy-name`} type="text" value={policyName} onChange={(e) => setPolicyName(e.target.value)} className="input-field" aria-label={`Policy name for ${toolName}`} />
          </div>

          {rules.map((rule, index) => (
            <div key={index} className="border border-gray-200 rounded-lg p-3 space-y-2">
              <div className="flex items-center gap-2">
                <label htmlFor={`${toolId}-path-${index}`} className="text-sm font-medium text-gray-700 whitespace-nowrap">Path:</label>
                <input id={`${toolId}-path-${index}`} type="text" value={rule.path} onChange={(e) => updatePath(index, e.target.value)} className="input-field flex-1" aria-label={`Rule path ${index + 1}`} placeholder="secret/data/my-app/*" />
                {rules.length > 1 && (
                  <button onClick={() => removeRule(index)} className="text-red-500 text-sm hover:text-red-700">Remove</button>
                )}
              </div>
              <div className="flex flex-wrap gap-2">
                {allCapabilities.map(cap => (
                  <label key={cap} className="flex items-center gap-1 text-xs">
                    <input type="checkbox" checked={rule.capabilities.includes(cap)} onChange={() => toggleCapability(index, cap)} className="rounded" />
                    {cap}
                  </label>
                ))}
              </div>
            </div>
          ))}

          <div className="flex gap-2">
            <button onClick={addRule} className="btn-secondary">Add Rule</button>
            <button onClick={generate} className="btn-primary">Generate Policy</button>
          </div>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated Vault Policy HCL</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 break-all bg-gray-50 p-4 rounded-lg">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
