'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

/**
 * ZookeeperConfigGenerator - Generate Apache ZooKeeper configuration files.
 * Supports standalone and ensemble modes with common configuration options.
 */
export default function ZookeeperConfigGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [tickTime, setTickTime] = useState('2000');
  const [dataDir, setDataDir] = useState('/var/lib/zookeeper');
  const [clientPort, setClientPort] = useState('2181');
  const [initLimit, setInitLimit] = useState('10');
  const [syncLimit, setSyncLimit] = useState('5');
  const [maxClientCnxns, setMaxClientCnxns] = useState('60');
  const [nodes, setNodes] = useState('1');
  const [autopurgeInterval, setAutopurgeInterval] = useState('1');
  const [autopurgeRetain, setAutopurgeRetain] = useState('3');
  const [output, setOutput] = useState('');

  const generate = () => {
    const nodeCount = Math.max(1, Math.min(9, parseInt(nodes) || 1));
    let config = `# Apache ZooKeeper Configuration\n`;
    config += `# Generated by DeWelope Tools\n\n`;
    config += `# Basic Settings\n`;
    config += `tickTime=${tickTime}\n`;
    config += `dataDir=${dataDir}\n`;
    config += `clientPort=${clientPort}\n`;
    config += `maxClientCnxns=${maxClientCnxns}\n\n`;

    if (nodeCount > 1) {
      config += `# Ensemble Settings\n`;
      config += `initLimit=${initLimit}\n`;
      config += `syncLimit=${syncLimit}\n\n`;
      config += `# Cluster Nodes\n`;
      for (let i = 1; i <= nodeCount; i++) {
        config += `server.${i}=zk-node-${i}:2888:3888\n`;
      }
      config += `\n`;
    }

    config += `# Autopurge Settings\n`;
    config += `autopurge.snapRetainCount=${autopurgeRetain}\n`;
    config += `autopurge.purgeInterval=${autopurgeInterval}\n\n`;
    config += `# Additional Settings\n`;
    config += `admin.enableServer=true\n`;
    config += `admin.serverPort=8080\n`;
    config += `4lw.commands.whitelist=mntr,conf,ruok\n`;

    setOutput(config);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor={`${toolId}-ticktime`} className="block text-sm font-medium text-gray-700 mb-1">Tick Time (ms)</label>
            <input id={`${toolId}-ticktime`} type="number" value={tickTime} onChange={(e) => setTickTime(e.target.value)} className="input-field" aria-label={`Tick time for ${toolName}`} />
          </div>
          <div>
            <label htmlFor={`${toolId}-datadir`} className="block text-sm font-medium text-gray-700 mb-1">Data Directory</label>
            <input id={`${toolId}-datadir`} type="text" value={dataDir} onChange={(e) => setDataDir(e.target.value)} className="input-field" aria-label="Data directory path" />
          </div>
          <div>
            <label htmlFor={`${toolId}-port`} className="block text-sm font-medium text-gray-700 mb-1">Client Port</label>
            <input id={`${toolId}-port`} type="number" value={clientPort} onChange={(e) => setClientPort(e.target.value)} className="input-field" aria-label="Client port number" />
          </div>
          <div>
            <label htmlFor={`${toolId}-nodes`} className="block text-sm font-medium text-gray-700 mb-1">Number of Nodes (1-9)</label>
            <input id={`${toolId}-nodes`} type="number" min="1" max="9" value={nodes} onChange={(e) => setNodes(e.target.value)} className="input-field" aria-label="Number of cluster nodes" />
          </div>
          <div>
            <label htmlFor={`${toolId}-initlimit`} className="block text-sm font-medium text-gray-700 mb-1">Init Limit</label>
            <input id={`${toolId}-initlimit`} type="number" value={initLimit} onChange={(e) => setInitLimit(e.target.value)} className="input-field" aria-label="Init limit" />
          </div>
          <div>
            <label htmlFor={`${toolId}-synclimit`} className="block text-sm font-medium text-gray-700 mb-1">Sync Limit</label>
            <input id={`${toolId}-synclimit`} type="number" value={syncLimit} onChange={(e) => setSyncLimit(e.target.value)} className="input-field" aria-label="Sync limit" />
          </div>
          <div>
            <label htmlFor={`${toolId}-maxclient`} className="block text-sm font-medium text-gray-700 mb-1">Max Client Connections</label>
            <input id={`${toolId}-maxclient`} type="number" value={maxClientCnxns} onChange={(e) => setMaxClientCnxns(e.target.value)} className="input-field" aria-label="Max client connections" />
          </div>
          <div>
            <label htmlFor={`${toolId}-purgeinterval`} className="block text-sm font-medium text-gray-700 mb-1">Autopurge Interval (hours)</label>
            <input id={`${toolId}-purgeinterval`} type="number" value={autopurgeInterval} onChange={(e) => setAutopurgeInterval(e.target.value)} className="input-field" aria-label="Autopurge interval" />
          </div>
          <div>
            <label htmlFor={`${toolId}-purgeretain`} className="block text-sm font-medium text-gray-700 mb-1">Autopurge Retain Count</label>
            <input id={`${toolId}-purgeretain`} type="number" value={autopurgeRetain} onChange={(e) => setAutopurgeRetain(e.target.value)} className="input-field" aria-label="Autopurge retain count" />
          </div>
        </div>
        <button onClick={generate} className="btn-primary mt-4">Generate Configuration</button>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">ZooKeeper Configuration (zoo.cfg)</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
