'use client';

import { useState } from 'react';
import InputArea from '@/components/tools/InputArea';
import OutputArea from '@/components/tools/OutputArea';
import CopyToClipboard from '@/components/tools/CopyToClipboard';

export default function CssFooterGenerator({ toolId, toolName }: { toolId: string; toolName: string }) {
  const [bgColor, setBgColor] = useState('#1a1a2e');
  const [textColor, setTextColor] = useState('#e0e0e0');
  const [linkColor, setLinkColor] = useState('#4fc3f7');
  const [columns, setColumns] = useState(3);
  const [padding, setPadding] = useState('40');
  const [fontSize, setFontSize] = useState('14');
  const [output, setOutput] = useState('');

  const generate = () => {
    const css = `/* Footer Styles - Generated by DeWelope Tools */
.footer {
  background-color: ${bgColor};
  color: ${textColor};
  padding: ${padding}px 20px;
  font-size: ${fontSize}px;
  line-height: 1.6;
}

.footer-container {
  max-width: 1200px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: repeat(${columns}, 1fr);
  gap: 30px;
}

.footer-column h3 {
  color: ${textColor};
  font-size: ${parseInt(fontSize) + 2}px;
  font-weight: 600;
  margin-bottom: 16px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.footer-column ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.footer-column ul li {
  margin-bottom: 8px;
}

.footer-column a {
  color: ${linkColor};
  text-decoration: none;
  transition: opacity 0.2s ease;
}

.footer-column a:hover {
  opacity: 0.8;
  text-decoration: underline;
}

.footer-bottom {
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  margin-top: 30px;
  padding-top: 20px;
  text-align: center;
  font-size: ${parseInt(fontSize) - 2}px;
  opacity: 0.7;
}

@media (max-width: 768px) {
  .footer-container {
    grid-template-columns: 1fr;
    gap: 20px;
  }
}`;

    const html = `<!-- Footer HTML -->
<footer class="footer">
  <div class="footer-container">
    <div class="footer-column">
      <h3>Company</h3>
      <ul>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h3>Resources</h3>
      <ul>
        <li><a href="#">Documentation</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Support</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h3>Legal</h3>
      <ul>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Cookie Policy</a></li>
      </ul>
    </div>
  </div>
  <div class="footer-bottom">
    <p>&copy; 2024 Your Company. All rights reserved.</p>
  </div>
</footer>`;

    setOutput(css + '\n\n' + html);
  };

  return (
    <div className="space-y-4" data-tool-id={toolId}>
      <InputArea>
        <div className="space-y-3">
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label htmlFor={`${toolId}-bg`} className="block text-sm font-medium text-gray-700 mb-1">Background</label>
              <input id={`${toolId}-bg`} type="color" value={bgColor} onChange={(e) => setBgColor(e.target.value)} className="input-field h-10" aria-label={`Background color for ${toolName}`} />
            </div>
            <div>
              <label htmlFor={`${toolId}-text`} className="block text-sm font-medium text-gray-700 mb-1">Text Color</label>
              <input id={`${toolId}-text`} type="color" value={textColor} onChange={(e) => setTextColor(e.target.value)} className="input-field h-10" aria-label="Text color" />
            </div>
            <div>
              <label htmlFor={`${toolId}-link`} className="block text-sm font-medium text-gray-700 mb-1">Link Color</label>
              <input id={`${toolId}-link`} type="color" value={linkColor} onChange={(e) => setLinkColor(e.target.value)} className="input-field h-10" aria-label="Link color" />
            </div>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label htmlFor={`${toolId}-cols`} className="block text-sm font-medium text-gray-700 mb-1">Columns</label>
              <input id={`${toolId}-cols`} type="number" value={columns} onChange={(e) => setColumns(Number(e.target.value))} min={1} max={6} className="input-field" aria-label="Columns" />
            </div>
            <div>
              <label htmlFor={`${toolId}-pad`} className="block text-sm font-medium text-gray-700 mb-1">Padding (px)</label>
              <input id={`${toolId}-pad`} type="number" value={padding} onChange={(e) => setPadding(e.target.value)} className="input-field" aria-label="Padding" />
            </div>
            <div>
              <label htmlFor={`${toolId}-font`} className="block text-sm font-medium text-gray-700 mb-1">Font Size (px)</label>
              <input id={`${toolId}-font`} type="number" value={fontSize} onChange={(e) => setFontSize(e.target.value)} className="input-field" aria-label="Font size" />
            </div>
          </div>
          <button onClick={generate} className="btn-primary">Generate Footer</button>
        </div>
      </InputArea>

      <OutputArea hasContent={!!output}>
        {output && (
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">Generated CSS + HTML</label>
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-800 bg-gray-50 p-4 rounded-lg overflow-x-auto max-h-96 overflow-y-auto">{output}</pre>
            <CopyToClipboard text={output} />
          </div>
        )}
      </OutputArea>
    </div>
  );
}
