const fs = require('fs');
const path = require('path');

const registryPath = path.join(__dirname, 'src/data/tools-registry.ts');
let content = fs.readFileSync(registryPath, 'utf8');

const newEntries = [
  `  { id: 'color-format-converter', name: 'Color Format Converter', description: 'Convert any hex color to all formats at once: HEX, RGB, RGBA, and HSL. Shows all representations simultaneously.', shortDescription: 'Convert between all color formats at once.', category: 'image-color-tools', slug: 'color-format-converter', metaTitle: 'Color Format Converter - Free Online Tool', metaDescription: 'Convert hex colors to RGB, RGBA, and HSL simultaneously. See all color formats at once. Free online color format converter.', keywords: ['color format', 'hex to rgb', 'hex to hsl', 'color converter', 'rgba', 'color codes'], featured: false, componentPath: '@/components/tools/image-color-tools/ColorFormatConverter', inputConfig: { type: 'composite', fields: [] }, outputConfig: { type: 'multi-value', copyable: true }, howToUse: 'Enter a hex color to see it converted to all common color formats simultaneously.', howToSteps: ['Enter a hex color code', 'Click Convert', 'View HEX, RGB, RGBA, and HSL values', 'Copy any format you need'] },`,
  `  { id: 'gradient-direction-picker', name: 'Gradient Direction Picker', description: 'Pick a CSS gradient angle visually with a slider. Choose two colors and see the gradient preview with generated CSS code.', shortDescription: 'Pick gradient angle visually.', category: 'image-color-tools', slug: 'gradient-direction-picker', metaTitle: 'Gradient Direction Picker - Free Online Tool', metaDescription: 'Pick CSS gradient angles visually with live preview. Generate gradient CSS code. Free online gradient direction tool.', keywords: ['gradient direction', 'gradient angle', 'css gradient', 'linear gradient', 'gradient picker'], featured: false, componentPath: '@/components/tools/image-color-tools/GradientDirectionPicker', inputConfig: { type: 'composite', fields: [] }, outputConfig: { type: 'text', copyable: true }, howToUse: 'Use the angle slider and color pickers to create a gradient and get the CSS code.', howToSteps: ['Adjust the angle slider (0-360)', 'Pick two colors', 'Preview the gradient', 'Copy the CSS code'] },`,
  `  { id: 'css-color-name-list', name: 'CSS Color Name List', description: 'Browse all 148 CSS named colors with visual swatches. Filter by name to find specific colors quickly.', shortDescription: 'Browse all 148 CSS named colors.', category: 'image-color-tools', slug: 'css-color-name-list', metaTitle: 'CSS Color Name List - Free Online Tool', metaDescription: 'Browse all 148 CSS named colors with swatches. Filter and find colors by name. Free online CSS color reference.', keywords: ['css colors', 'named colors', 'color names', 'css color list', 'web colors', 'color reference'], featured: false, componentPath: '@/components/tools/image-color-tools/CssColorNameList', inputConfig: { type: 'text', maxLength: 100 }, outputConfig: { type: 'text', copyable: true }, howToUse: 'Browse or filter the complete list of 148 CSS named colors with visual swatches.', howToSteps: ['Browse the color list', 'Use the filter to search by name', 'View color swatches', 'Copy color names for your CSS'] },`,
];

// Insert before the closing ];
content = content.replace(/\n];(\n\n\/\/ =)/, '\n' + newEntries.join('\n') + '\n];\n\n// =');
fs.writeFileSync(registryPath, content);
console.log('Added 3 missing registry entries');
